In [1]:
import numpy as np
import pandas as pd
from sklearn.neighbors import KNeighborsClassifier
from sklearn.discriminant_analysis import LinearDiscriminantAnalysis, QuadraticDiscriminantAnalysis
from sklearn.linear_model import LogisticRegression
from sklearn.naive_bayes import GaussianNB
from sklearn.ensemble import RandomForestClassifier
from xgboost import XGBClassifier
from sklearn.gaussian_process import GaussianProcessClassifier
from sklearn.gaussian_process.kernels import Matern, RationalQuadratic, RBF
from src.models.mlp import create_mlp_pytorch
from src.models.resnet import ResBlock, ResNet
from sklearn.utils import resample
from sklearn.preprocessing import StandardScaler
from sklearn.metrics import roc_auc_score
from sklearn.model_selection import ParameterGrid
import shap

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/tqdm/auto.py:21: TqdmWarning: IProgress not found. Please update jupyter and ipywidgets. See https://ipywidgets.readthedocs.io/en/stable/user_install.html
  from .autonotebook import tqdm as notebook_tqdm

In [2]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from typing import Tuple, List, Optional
from copy import deepcopy

class EarlyStopping:
    """Early stopping to stop training when validation loss doesn't improve."""
    def __init__(self, patience: int = 10, min_delta: float = 0.0, verbose: bool = False):
        """
        Args:
            patience: Number of epochs to wait after last improvement
            min_delta: Minimum change to qualify as improvement
            verbose: If True, prints early stopping messages
        """
        self.patience = patience
        self.min_delta = min_delta
        self.verbose = verbose
        self.counter = 0
        self.best_loss = float('inf')
        self.early_stop = False
        self.best_model_state = None
        
    def __call__(self, val_loss: float, model: nn.Module) -> bool:
        """
        Check if training should stop early.
        
        Returns:
            True if training should stop, False otherwise
        """
        if val_loss < self.best_loss - self.min_delta:
            if self.verbose:
                print(f'Validation loss decreased ({self.best_loss:.6f} -> {val_loss:.6f}). Saving model...')
            self.best_loss = val_loss
            self.counter = 0
            # Save the best model state
            self.best_model_state = deepcopy(model.state_dict())
            return False
        else:
            self.counter += 1
            if self.verbose:
                print(f'EarlyStopping counter: {self.counter} out of {self.patience}')
            if self.counter >= self.patience:
                self.early_stop = True
                if self.verbose:
                    print("Early stopping triggered")
            return self.early_stop

In [3]:
descriptor_df = pd.read_csv('data/bace/external_descriptors.csv')
smiles_df = pd.read_csv('data/bace/smiles.csv')
learned_descriptors_df = pd.read_csv('data/bace/learned_predictors_0.csv')

In [4]:
import pandas as pd
from rdkit import Chem
from rdkit.Chem.Scaffolds import MurckoScaffold
from sklearn.model_selection import GroupShuffleSplit
import numpy as np

class ScaffoldSplitter:
    """Comprehensive scaffold splitter with train/val/test splits."""
    
    def __init__(self, random_state=42):
        self.random_state = random_state
        np.random.seed(random_state)
    
    def get_scaffold(self, smiles):
        """Extract scaffold from SMILES."""
        try:
            mol = Chem.MolFromSmiles(smiles)
            if mol is None:
                return "invalid"
            scaffold = MurckoScaffold.GetScaffoldForMol(mol)
            return Chem.MolToSmiles(scaffold)
        except:
            return "invalid"
    
    def split(self, smiles_list, y=None, 
              train_ratio=0.8, val_ratio=0.1, test_ratio=0.1):
        """
        Split into train/validation/test sets by scaffold.
        
        Args:
            smiles_list: List of SMILES strings
            y: Target values (optional)
            train_ratio, val_ratio, test_ratio: Split ratios
            
        Returns:
            Indices for each split
        """
        # Generate scaffolds
        scaffolds = [self.get_scaffold(s) for s in smiles_list]
        
        # Create groups dictionary
        scaffold_to_indices = {}
        for idx, scaffold in enumerate(scaffolds):
            if scaffold not in scaffold_to_indices:
                scaffold_to_indices[scaffold] = []
            scaffold_to_indices[scaffold].append(idx)
        
        # Sort scaffolds by number of molecules (descending)
        sorted_scaffolds = sorted(scaffold_to_indices.items(),
                                 key=lambda x: len(x[1]), reverse=True)
        
        # Initialize split indices
        train_idx, val_idx, test_idx = [], [], []
        
        # Distribute scaffolds to splits
        for scaffold, indices in sorted_scaffolds:
            if len(train_idx) / len(smiles_list) < train_ratio:
                train_idx.extend(indices)
            elif len(val_idx) / len(smiles_list) < val_ratio:
                val_idx.extend(indices)
            else:
                test_idx.extend(indices)
        
        # Shuffle indices
        np.random.shuffle(train_idx)
        np.random.shuffle(val_idx)
        np.random.shuffle(test_idx)
        
        return train_idx, val_idx, test_idx

In [5]:
# Create splitter
splitter = ScaffoldSplitter(random_state=42)

# Get split indices
train_idx, val_idx, test_idx = splitter.split(
    smiles_df['ids'].tolist(),
    y=smiles_df['y'].tolist(),
    train_ratio=0.6,
    val_ratio=0.2,
    test_ratio=0.2)

In [6]:
smiles_df_train = smiles_df.iloc[train_idx].reset_index(drop=True)
smiles_df_val = smiles_df.iloc[val_idx].reset_index(drop=True)
smiles_df_test = smiles_df.iloc[test_idx].reset_index(drop=True)

In [7]:


descriptor_df_train = descriptor_df.iloc[train_idx].reset_index(drop=True)
descriptor_df_val = descriptor_df.iloc[val_idx].reset_index(drop=True)
descriptor_df_test = descriptor_df.iloc[test_idx].reset_index(drop=True)

In [8]:
learned_descriptors_df_train = learned_descriptors_df.iloc[train_idx].reset_index()
learned_descriptors_df_val = learned_descriptors_df.iloc[val_idx].reset_index()
learned_descriptors_df_test = learned_descriptors_df.iloc[test_idx].reset_index()

In [9]:
df_train = pd.concat([learned_descriptors_df_train, descriptor_df_train, smiles_df_train], axis=1)
df_val = pd.concat([learned_descriptors_df_val, descriptor_df_val, smiles_df_val], axis=1)
df_test = pd.concat([learned_descriptors_df_test, descriptor_df_test, smiles_df_test],axis=1)

In [10]:
df_train.head()

,index,fp_0,fp_1,fp_2,fp_3,fp_4,fp_5,fp_6,fp_7,fp_8,...,209,210,211,212,213,214,215,y,w,ids
0,1011,0.015950,0.0,0.132767,0.047984,0.044219,0.000000,0.048745,0.011339,0.000234,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.844512,O=C1N(C)C(=N[C@@](C1)(CCc1ccccc1)C)N
1,490,0.048197,0.0,0.204776,0.072178,0.073979,0.000125,0.032347,0.004190,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.844512,n1ccc(cc1)C1(N=C(N)c2c1cccc2)c1cc(ccc1)-c1cncnc1
2,1210,0.028600,0.0,0.238802,0.090424,0.082761,0.000000,0.090894,0.025848,0.000116,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.844512,S1(=O)CC(Cc2cc(O)c(N)c(F)c2)C(O)C([NH2+]Cc2cc(...
3,717,0.056243,0.0,0.239946,0.084071,0.087759,0.000010,0.037141,0.006602,0.000567,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,2.184116,Clc1ccccc1-c1n(Cc2nc(N)ccc2)c(cc1)-c1ccc(Oc2cn...
4,944,0.038900,0.0,0.210920,0.079502,0.077362,0.000226,0.053684,0.016053,0.000000,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.844512,Fc1ncccc1-c1cc(ccc1)C1(N=C(OC1)N)c1ccc(OC(F)F)cc1

In [11]:
X_train = df_train.drop(columns=['y', 'w', 'ids'])
y_train = df_train['y']
X_val = df_val.drop(columns=['y', 'ids', 'w'])
y_val = df_val['y']
X_test = df_test.drop(columns=['y', 'ids', 'w'])
y_test = df_test['y']

In [12]:
base_seed = 42
config_id = 0
models_list = []

In [13]:
for i in range(4):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = KNeighborsClassifier()
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': {},
        'roc': roc
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 0, 'model_type': 'KNeighborsClassifier', 'hyperparams': {}, 'roc': 0.7673527037933817}
{'index': 1, 'model_type': 'KNeighborsClassifier', 'hyperparams': {}, 'roc': 0.7045332257196664}
{'index': 2, 'model_type': 'KNeighborsClassifier', 'hyperparams': {}, 'roc': 0.7554479418886199}
{'index': 3, 'model_type': 'KNeighborsClassifier', 'hyperparams': {}, 'roc': 0.7288808178638687}

In [14]:
for i in range(4):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = LinearDiscriminantAnalysis()
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': {},
        'roc': roc
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 4, 'model_type': 'LinearDiscriminantAnalysis', 'hyperparams': {}, 'roc': 0.5936911487758946}
{'index': 5, 'model_type': 'LinearDiscriminantAnalysis', 'hyperparams': {}, 'roc': 0.5268361581920904}
{'index': 6, 'model_type': 'LinearDiscriminantAnalysis', 'hyperparams': {}, 'roc': 0.5813828356201237}
{'index': 7, 'model_type': 'LinearDiscriminantAnalysis', 'hyperparams': {}, 'roc': 0.5607344632768362}

In [15]:
param_grid = {
    'reg_param': [0.1, 0.2, 0.5, 1]
}

for params in ParameterGrid(param_grid):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = QuadraticDiscriminantAnalysis(**params)
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'roc': roc
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 8, 'model_type': 'QuadraticDiscriminantAnalysis', 'hyperparams': {'reg_param': 0.1}, 'roc': 0.6997578692493946}
{'index': 9, 'model_type': 'QuadraticDiscriminantAnalysis', 'hyperparams': {'reg_param': 0.2}, 'roc': 0.6098331988162498}
{'index': 10, 'model_type': 'QuadraticDiscriminantAnalysis', 'hyperparams': {'reg_param': 0.5}, 'roc': 0.709712133440947}
{'index': 11, 'model_type': 'QuadraticDiscriminantAnalysis', 'hyperparams': {'reg_param': 1}, 'roc': 0.6486413774549368}

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 0 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/discriminant_analysis.py:1024: LinAlgWarning: The covariance matrix of class 1 is not full rank. Increasing the value of parameter `reg_param` might help reducing the collinearity.
  warnings.warn(

In [16]:
for i in range(4):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = LogisticRegression()
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': {},
        'roc': roc
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 12, 'model_type': 'LogisticRegression', 'hyperparams': {}, 'roc': 0.730562281409739}
{'index': 13, 'model_type': 'LogisticRegression', 'hyperparams': {}, 'roc': 0.7106537530266344}
{'index': 14, 'model_type': 'LogisticRegression', 'hyperparams': {}, 'roc': 0.6602771051923594}
{'index': 15, 'model_type': 'LogisticRegression', 'hyperparams': {}, 'roc': 0.716908797417272}

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_logistic.py:473: ConvergenceWarning: lbfgs failed to converge after 100 iteration(s) (status=1):
STOP: TOTAL NO. OF ITERATIONS REACHED LIMIT

Increase the number of iterations to improve the convergence (max_iter=100).
You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
Please also refer to the documentation for alternative solver options:
    https://scikit-learn.org/stable/modules/linear_model.html#logistic-regression
  n_iter_i = _check_optimize_result(

In [17]:
for i in range(4):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = GaussianNB()
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': {},
        'roc': roc
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 16, 'model_type': 'GaussianNB', 'hyperparams': {}, 'roc': 0.6613532418617165}
{'index': 17, 'model_type': 'GaussianNB', 'hyperparams': {}, 'roc': 0.6177024482109228}
{'index': 18, 'model_type': 'GaussianNB', 'hyperparams': {}, 'roc': 0.6698278181329029}
{'index': 19, 'model_type': 'GaussianNB', 'hyperparams': {}, 'roc': 0.5901937046004843}

In [18]:
import time

In [19]:
hyperparams_list = [
    {'max_depth': 5, 'n_estimators': 10, 'learning_rate': 0.01},
    {'max_depth': 10, 'n_estimators': 10, 'learning_rate': 0.01},
    {'max_depth': 10, 'n_estimators': 100, 'learning_rate': 0.1},
    {'max_depth': 10, 'n_estimators': 100, 'learning_rate': 0.01},
    {'max_depth': 3, 'n_estimators': 500, 'learning_rate': 0.1},
    {'max_depth': 3, 'n_estimators': 500, 'learning_rate': 0.2},
    {'max_depth': 3, 'n_estimators': 1000, 'learning_rate': 0.1},
    {'max_depth': 10, 'n_estimators': 2000, 'learning_rate': 0.2}
]

for idx, params in enumerate(hyperparams_list):

    seed = base_seed + config_id

    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)

    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)

    start_time = time.time()
    model = XGBClassifier(
        max_depth=params['max_depth'],
        n_estimators=params['n_estimators'],
        learning_rate=params['learning_rate'],
        n_jobs=-1,
    )

    model.fit(X_boot_scaled, y_boot)

    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    
    roc = float(roc_auc_score(y_val, y_val_pred))
    training_time = time.time() - start_time
    
    print(f'Training time: {training_time}')
    
    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'roc': roc
    }
    
    config_id += 1
    
    print(model_metadata)
    
    models_list.append(model_metadata)

Training time: 0.08070802688598633
{'index': 20, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 5, 'n_estimators': 10, 'learning_rate': 0.01}, 'roc': 0.6503228410008071}
Training time: 0.12401723861694336
{'index': 21, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 10, 'n_estimators': 10, 'learning_rate': 0.01}, 'roc': 0.6264460586494485}
Training time: 0.5544490814208984
{'index': 22, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 10, 'n_estimators': 100, 'learning_rate': 0.1}, 'roc': 0.7565240785579769}
Training time: 0.772442102432251
{'index': 23, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 10, 'n_estimators': 100, 'learning_rate': 0.01}, 'roc': 0.7350013451708366}
Training time: 0.6932089328765869
{'index': 24, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 3, 'n_estimators': 500, 'learning_rate': 0.1}, 'roc': 0.7452246435297283}
Training time: 0.588068962097168
{'index': 25, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 3, 'n_estimators': 500, 'learning_rate': 0.2}, 'roc': 0.7304950228679041}
Training time: 1.196986436843872
{'index': 26, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 3, 'n_estimators': 1000, 'learning_rate': 0.1}, 'roc': 0.6998923863330643}
Training time: 2.0140113830566406
{'index': 27, 'model_type': 'XGBClassifier', 'hyperparams': {'max_depth': 10, 'n_estimators': 2000, 'learning_rate': 0.2}, 'roc': 0.7384315308044122}

In [20]:
param_grid = [
    # Matern kernel models
    {
        'kernel': Matern(),  
    },
    {
        'kernel': Matern(),  
    },
    # Quadratic (RBF) kernel models  
    {
        'kernel': RBF(),  
    },
    {
        'kernel': RBF(),
    },
    #RationalQuadratic kernel model
    {
        'kernel': RationalQuadratic()
    },
    {
        'kernel': RationalQuadratic()
    }
]

for idx, params in enumerate(param_grid):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    start_time = time.time()
    model = GaussianProcessClassifier(kernel=params['kernel'])
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    roc = float(roc_auc_score(y_val, y_val_pred))
    training_time = time.time() - start_time
    print(f'Training time: {training_time}')
    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'roc': roc 
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

Training time: 1.687493085861206
{'index': 28, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)}, 'roc': 0.698210922787194}
Training time: 1.6234090328216553
{'index': 29, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)}, 'roc': 0.7135458703255313}
Training time: 2.3089332580566406
{'index': 30, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': RBF(length_scale=1)}, 'roc': 0.6898036050578424}
Training time: 3.0308525562286377
{'index': 31, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': RBF(length_scale=1)}, 'roc': 0.7209443099273607}
Training time: 3.725635051727295
{'index': 32, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': RationalQuadratic(alpha=1, length_scale=1)}, 'roc': 0.6959913909066452}
Training time: 4.171703815460205
{'index': 33, 'model_type': 'GaussianProcessClassifier', 'hyperparams': {'kernel': RationalQuadratic(alpha=1, length_scale=1)}, 'roc': 0.7124697336561744}

In [21]:
import torch
import torch.nn as nn
import torch.optim as optim
import numpy as np
from typing import Tuple, List, Optional
from copy import deepcopy

class MLP(nn.Module):
    def __init__(self, input_dim, output_dim, n_layers=2, layer_size=5):
        super().__init__()
        
        
        layers = []
        
        # Input layer
        layers.append(nn.Linear(input_dim, layer_size))
        layers.append(nn.ReLU())
        
        # Hidden layers (n_layers - 1 additional hidden layers)
        for _ in range(n_layers - 1):
            layers.append(nn.Linear(layer_size, layer_size))
            layers.append(nn.ReLU())

        # Output layer
        layers.append(nn.Linear(layer_size, output_dim))
        # layers.append(nn.Sigmoid())
        
        self.model = nn.Sequential(*layers)
    
    def forward(self, x):
        return self.model(x)
        

def create_mlp_pytorch(input_dim, output_dim, n_layers=2, layer_size=5, 
                       lr=0.01, l2_reg=0.01):
    """
    Create MLP with specified parameters
    
    Args:
        input_dim: Input dimension
        output_dim: Output dimension
        n_layers: Number of hidden layers
        layer_size: Number of units per hidden layer
        lr: Learning rate
        l2_reg: L2 regularization strength (weight_decay)
    """
    model = MLP(input_dim, output_dim, n_layers, layer_size)
    optimizer = optim.Adam(model.parameters(), lr=lr, weight_decay=l2_reg)
    
    return model, optimizer

In [22]:
from torch.utils.data import DataLoader, TensorDataset

In [23]:
hyperparams_list = [
    {'n_layers': 2, 'layer_size': 5, 'lr': 0.01, 'l2_reg': 0.01},
    {'n_layers': 2, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1},
    {'n_layers': 3, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1},
    {'n_layers': 3, 'layer_size': 10, 'lr': 0.0005, 'l2_reg': 0.1}
]

for idx, params in enumerate(hyperparams_list):
    
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    params.update({
    'input_dim': X_boot.shape[1],
    'output_dim': 1
})
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)

    X_boot_tensor = torch.FloatTensor(X_boot_scaled)
    y_boot_tensor = torch.FloatTensor(y_boot.values)
    train_dataset = TensorDataset(X_boot_tensor, y_boot_tensor)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    X_val_scaled = scaler.transform(X_val)
    X_val_tensor = torch.FloatTensor(X_val_scaled)
    y_val_tensor = torch.FloatTensor(y_val.values)
    val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
    val_loader = DataLoader(val_dataset, batch_size=32)

    # Create MLP
    model, optimizer = create_mlp_pytorch(
        params['input_dim'],
        params['output_dim'], 
        n_layers=params['n_layers'],
        layer_size=params['layer_size'],
        lr=params['lr'],
        l2_reg=params['l2_reg'])
    
    # Training code would go here
    # model.train() ... etc.
    # Basic EarlyStopping for 1000 epochs
    early_stopping = EarlyStopping(patience=20, min_delta=0.001, verbose=True)
    criterion = nn.BCEWithLogitsLoss()
  
    train_losses = []
    val_losses = []
    
    for epoch in range(1000):
        # Training phase
        model.train()
        train_loss = 0.0
        for batch_idx, (data, target) in enumerate(train_loader):
            
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(input=output.squeeze(), target=target)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        avg_train_loss = train_loss / len(train_loader)
        train_losses.append(avg_train_loss)
        
        # Validation phase
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for data, target in val_loader:
                output = model(data)
                val_loss += criterion(input=output.squeeze(), target=target).item()
        
        avg_val_loss = val_loss / len(val_loader)
        val_losses.append(avg_val_loss)
        
        print(f'Epoch {epoch+1}/{1000}, '
                f'Train Loss: {avg_train_loss:.4f}, '
                f'Val Loss: {avg_val_loss:.4f}')
        
        # Early stopping check
        if early_stopping(avg_val_loss, model):
            print("Early stopping triggered. Restoring best model...")
            # Restore the best model
            model.load_state_dict(early_stopping.best_model_state)
            break
    
    model.eval()

    all_predictions = []
    all_targets = []

    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(val_loader):
            predictions = model(data)
            
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(target.numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions, axis=0)
    all_targets = np.concatenate(all_targets, axis=0)

    # Calculate RMSE
    roc = float(roc_auc_score(all_targets, all_predictions))
    
    # Store metadata
    model_metadata = {
        'index': config_id,
        'model_type': 'MLP_PyTorch',
        'hyperparams': params,
        'roc': roc
    }
    config_id += 1
    print(model_metadata)
    models_list.append(model_metadata)

Epoch 1/1000, Train Loss: 0.5966, Val Loss: 0.5886
Validation loss decreased (inf -> 0.588624). Saving model...
Epoch 2/1000, Train Loss: 0.4605, Val Loss: 0.6357
EarlyStopping counter: 1 out of 20
Epoch 3/1000, Train Loss: 0.3982, Val Loss: 0.6185
EarlyStopping counter: 2 out of 20
Epoch 4/1000, Train Loss: 0.3813, Val Loss: 0.6453
EarlyStopping counter: 3 out of 20
Epoch 5/1000, Train Loss: 0.3806, Val Loss: 0.6991
EarlyStopping counter: 4 out of 20
Epoch 6/1000, Train Loss: 0.3403, Val Loss: 0.6796
EarlyStopping counter: 5 out of 20
Epoch 7/1000, Train Loss: 0.3280, Val Loss: 0.6679
EarlyStopping counter: 6 out of 20
Epoch 8/1000, Train Loss: 0.3152, Val Loss: 0.6786
EarlyStopping counter: 7 out of 20
Epoch 9/1000, Train Loss: 0.3386, Val Loss: 0.7068
EarlyStopping counter: 8 out of 20
Epoch 10/1000, Train Loss: 0.3039, Val Loss: 0.6570
EarlyStopping counter: 9 out of 20
Epoch 11/1000, Train Loss: 0.3452, Val Loss: 0.6037
EarlyStopping counter: 10 out of 20
Epoch 12/1000, Train Loss: 0.3410, Val Loss: 0.6631
EarlyStopping counter: 11 out of 20
Epoch 13/1000, Train Loss: 0.3101, Val Loss: 0.6383
EarlyStopping counter: 12 out of 20
Epoch 14/1000, Train Loss: 0.2807, Val Loss: 0.6849
EarlyStopping counter: 13 out of 20
Epoch 15/1000, Train Loss: 0.3074, Val Loss: 0.7297
EarlyStopping counter: 14 out of 20
Epoch 16/1000, Train Loss: 0.3547, Val Loss: 0.7148
EarlyStopping counter: 15 out of 20
Epoch 17/1000, Train Loss: 0.3406, Val Loss: 0.6439
EarlyStopping counter: 16 out of 20
Epoch 18/1000, Train Loss: 0.2902, Val Loss: 0.6910
EarlyStopping counter: 17 out of 20
Epoch 19/1000, Train Loss: 0.3170, Val Loss: 0.6934
EarlyStopping counter: 18 out of 20
Epoch 20/1000, Train Loss: 0.2969, Val Loss: 0.6662
EarlyStopping counter: 19 out of 20
Epoch 21/1000, Train Loss: 0.2970, Val Loss: 0.6323
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 34, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 2, 'layer_size': 5, 'lr': 0.01, 'l2_reg': 0.01, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.7729575822796162}
Epoch 1/1000, Train Loss: 0.6546, Val Loss: 0.6134
Validation loss decreased (inf -> 0.613354). Saving model...
Epoch 2/1000, Train Loss: 0.5876, Val Loss: 0.5863
Validation loss decreased (0.613354 -> 0.586348). Saving model...
Epoch 3/1000, Train Loss: 0.5467, Val Loss: 0.5695
Validation loss decreased (0.586348 -> 0.569537). Saving model...
Epoch 4/1000, Train Loss: 0.5146, Val Loss: 0.5581
Validation loss decreased (0.569537 -> 0.558125). Saving model...
Epoch 5/1000, Train Loss: 0.4889, Val Loss: 0.5545
Validation loss decreased (0.558125 -> 0.554525). Saving model...
Epoch 6/1000, Train Loss: 0.4750, Val Loss: 0.5548
EarlyStopping counter: 1 out of 20
Epoch 7/1000, Train Loss: 0.4586, Val Loss: 0.5520
Validation loss decreased (0.554525 -> 0.551958). Saving model...
Epoch 8/1000, Train Loss: 0.4390, Val Loss: 0.5530
EarlyStopping counter: 1 out of 20
Epoch 9/1000, Train Loss: 0.4288, Val Loss: 0.5401
Validation loss decreased (0.551958 -> 0.540143). Saving model...
Epoch 10/1000, Train Loss: 0.4202, Val Loss: 0.5354
Validation loss decreased (0.540143 -> 0.535400). Saving model...
Epoch 11/1000, Train Loss: 0.4037, Val Loss: 0.5480
EarlyStopping counter: 1 out of 20
Epoch 12/1000, Train Loss: 0.4027, Val Loss: 0.5262
Validation loss decreased (0.535400 -> 0.526217). Saving model...
Epoch 13/1000, Train Loss: 0.3964, Val Loss: 0.5311
EarlyStopping counter: 1 out of 20
Epoch 14/1000, Train Loss: 0.3927, Val Loss: 0.5324
EarlyStopping counter: 2 out of 20
Epoch 15/1000, Train Loss: 0.3870, Val Loss: 0.5323
EarlyStopping counter: 3 out of 20
Epoch 16/1000, Train Loss: 0.3807, Val Loss: 0.5272
EarlyStopping counter: 4 out of 20
Epoch 17/1000, Train Loss: 0.3788, Val Loss: 0.5523
EarlyStopping counter: 5 out of 20
Epoch 18/1000, Train Loss: 0.3729, Val Loss: 0.5339
EarlyStopping counter: 6 out of 20
Epoch 19/1000, Train Loss: 0.3776, Val Loss: 0.5277
EarlyStopping counter: 7 out of 20
Epoch 20/1000, Train Loss: 0.3704, Val Loss: 0.5362
EarlyStopping counter: 8 out of 20
Epoch 21/1000, Train Loss: 0.3687, Val Loss: 0.5341
EarlyStopping counter: 9 out of 20
Epoch 22/1000, Train Loss: 0.3764, Val Loss: 0.5377
EarlyStopping counter: 10 out of 20
Epoch 23/1000, Train Loss: 0.3676, Val Loss: 0.5298
EarlyStopping counter: 11 out of 20
Epoch 24/1000, Train Loss: 0.3603, Val Loss: 0.5286
EarlyStopping counter: 12 out of 20
Epoch 25/1000, Train Loss: 0.3700, Val Loss: 0.5341
EarlyStopping counter: 13 out of 20
Epoch 26/1000, Train Loss: 0.3683, Val Loss: 0.5302
EarlyStopping counter: 14 out of 20
Epoch 27/1000, Train Loss: 0.3617, Val Loss: 0.5459
EarlyStopping counter: 15 out of 20
Epoch 28/1000, Train Loss: 0.3525, Val Loss: 0.5483
EarlyStopping counter: 16 out of 20
Epoch 29/1000, Train Loss: 0.3560, Val Loss: 0.5243
Validation loss decreased (0.526217 -> 0.524310). Saving model...
Epoch 30/1000, Train Loss: 0.3563, Val Loss: 0.5210
Validation loss decreased (0.524310 -> 0.521041). Saving model...
Epoch 31/1000, Train Loss: 0.3485, Val Loss: 0.5452
EarlyStopping counter: 1 out of 20
Epoch 32/1000, Train Loss: 0.3507, Val Loss: 0.5203
EarlyStopping counter: 2 out of 20
Epoch 33/1000, Train Loss: 0.3480, Val Loss: 0.5319
EarlyStopping counter: 3 out of 20
Epoch 34/1000, Train Loss: 0.3448, Val Loss: 0.5277
EarlyStopping counter: 4 out of 20
Epoch 35/1000, Train Loss: 0.3417, Val Loss: 0.5362
EarlyStopping counter: 5 out of 20
Epoch 36/1000, Train Loss: 0.3527, Val Loss: 0.5258
EarlyStopping counter: 6 out of 20
Epoch 37/1000, Train Loss: 0.3468, Val Loss: 0.5272
EarlyStopping counter: 7 out of 20
Epoch 38/1000, Train Loss: 0.3402, Val Loss: 0.5236
EarlyStopping counter: 8 out of 20
Epoch 39/1000, Train Loss: 0.3401, Val Loss: 0.5220
EarlyStopping counter: 9 out of 20
Epoch 40/1000, Train Loss: 0.3418, Val Loss: 0.5203
EarlyStopping counter: 10 out of 20
Epoch 41/1000, Train Loss: 0.3407, Val Loss: 0.5359
EarlyStopping counter: 11 out of 20
Epoch 42/1000, Train Loss: 0.3397, Val Loss: 0.5438
EarlyStopping counter: 12 out of 20
Epoch 43/1000, Train Loss: 0.3360, Val Loss: 0.5232
EarlyStopping counter: 13 out of 20
Epoch 44/1000, Train Loss: 0.3377, Val Loss: 0.5279
EarlyStopping counter: 14 out of 20
Epoch 45/1000, Train Loss: 0.3390, Val Loss: 0.5253
EarlyStopping counter: 15 out of 20
Epoch 46/1000, Train Loss: 0.3349, Val Loss: 0.5255
EarlyStopping counter: 16 out of 20
Epoch 47/1000, Train Loss: 0.3399, Val Loss: 0.5228
EarlyStopping counter: 17 out of 20
Epoch 48/1000, Train Loss: 0.3421, Val Loss: 0.5206
EarlyStopping counter: 18 out of 20
Epoch 49/1000, Train Loss: 0.3334, Val Loss: 0.5414
EarlyStopping counter: 19 out of 20
Epoch 50/1000, Train Loss: 0.3378, Val Loss: 0.5248
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 35, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 2, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.8072370191014259}
Epoch 1/1000, Train Loss: 0.6961, Val Loss: 0.7058
Validation loss decreased (inf -> 0.705755). Saving model...
Epoch 2/1000, Train Loss: 0.6850, Val Loss: 0.6959
Validation loss decreased (0.705755 -> 0.695945). Saving model...
Epoch 3/1000, Train Loss: 0.6815, Val Loss: 0.6938
Validation loss decreased (0.695945 -> 0.693811). Saving model...
Epoch 4/1000, Train Loss: 0.6806, Val Loss: 0.6925
Validation loss decreased (0.693811 -> 0.692506). Saving model...
Epoch 5/1000, Train Loss: 0.6818, Val Loss: 0.6927
EarlyStopping counter: 1 out of 20
Epoch 6/1000, Train Loss: 0.6839, Val Loss: 0.6949
EarlyStopping counter: 2 out of 20
Epoch 7/1000, Train Loss: 0.6859, Val Loss: 0.6962
EarlyStopping counter: 3 out of 20
Epoch 8/1000, Train Loss: 0.6888, Val Loss: 0.6988
EarlyStopping counter: 4 out of 20
Epoch 9/1000, Train Loss: 0.6913, Val Loss: 0.7006
EarlyStopping counter: 5 out of 20
Epoch 10/1000, Train Loss: 0.6931, Val Loss: 0.7012
EarlyStopping counter: 6 out of 20
Epoch 11/1000, Train Loss: 0.6930, Val Loss: 0.7012
EarlyStopping counter: 7 out of 20
Epoch 12/1000, Train Loss: 0.6940, Val Loss: 0.7011
EarlyStopping counter: 8 out of 20
Epoch 13/1000, Train Loss: 0.6940, Val Loss: 0.7004
EarlyStopping counter: 9 out of 20
Epoch 14/1000, Train Loss: 0.6934, Val Loss: 0.6997
EarlyStopping counter: 10 out of 20
Epoch 15/1000, Train Loss: 0.6939, Val Loss: 0.6996
EarlyStopping counter: 11 out of 20
Epoch 16/1000, Train Loss: 0.6930, Val Loss: 0.6986
EarlyStopping counter: 12 out of 20
Epoch 17/1000, Train Loss: 0.6933, Val Loss: 0.6984
EarlyStopping counter: 13 out of 20
Epoch 18/1000, Train Loss: 0.6930, Val Loss: 0.6980
EarlyStopping counter: 14 out of 20
Epoch 19/1000, Train Loss: 0.6935, Val Loss: 0.6980
EarlyStopping counter: 15 out of 20
Epoch 20/1000, Train Loss: 0.6932, Val Loss: 0.6975
EarlyStopping counter: 16 out of 20
Epoch 21/1000, Train Loss: 0.6934, Val Loss: 0.6972
EarlyStopping counter: 17 out of 20
Epoch 22/1000, Train Loss: 0.6933, Val Loss: 0.6968
EarlyStopping counter: 18 out of 20
Epoch 23/1000, Train Loss: 0.6932, Val Loss: 0.6965
EarlyStopping counter: 19 out of 20
Epoch 24/1000, Train Loss: 0.6932, Val Loss: 0.6963
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 36, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 3, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.7493498340955967}
Epoch 1/1000, Train Loss: 0.7085, Val Loss: 0.7233
Validation loss decreased (inf -> 0.723292). Saving model...
Epoch 2/1000, Train Loss: 0.7020, Val Loss: 0.7192
Validation loss decreased (0.723292 -> 0.719152). Saving model...
Epoch 3/1000, Train Loss: 0.6996, Val Loss: 0.7160
Validation loss decreased (0.719152 -> 0.715952). Saving model...
Epoch 4/1000, Train Loss: 0.6971, Val Loss: 0.7136
Validation loss decreased (0.715952 -> 0.713570). Saving model...
Epoch 5/1000, Train Loss: 0.6961, Val Loss: 0.7114
Validation loss decreased (0.713570 -> 0.711434). Saving model...
Epoch 6/1000, Train Loss: 0.6963, Val Loss: 0.7098
Validation loss decreased (0.711434 -> 0.709831). Saving model...
Epoch 7/1000, Train Loss: 0.6934, Val Loss: 0.7083
Validation loss decreased (0.709831 -> 0.708347). Saving model...
Epoch 8/1000, Train Loss: 0.6946, Val Loss: 0.7074
EarlyStopping counter: 1 out of 20
Epoch 9/1000, Train Loss: 0.6947, Val Loss: 0.7065
Validation loss decreased (0.708347 -> 0.706454). Saving model...
Epoch 10/1000, Train Loss: 0.6950, Val Loss: 0.7055
EarlyStopping counter: 1 out of 20
Epoch 11/1000, Train Loss: 0.6959, Val Loss: 0.7047
Validation loss decreased (0.706454 -> 0.704704). Saving model...
Epoch 12/1000, Train Loss: 0.6953, Val Loss: 0.7037
Validation loss decreased (0.704704 -> 0.703665). Saving model...
Epoch 13/1000, Train Loss: 0.6959, Val Loss: 0.7031
EarlyStopping counter: 1 out of 20
Epoch 14/1000, Train Loss: 0.6953, Val Loss: 0.7024
Validation loss decreased (0.703665 -> 0.702362). Saving model...
Epoch 15/1000, Train Loss: 0.6954, Val Loss: 0.7021
EarlyStopping counter: 1 out of 20
Epoch 16/1000, Train Loss: 0.6962, Val Loss: 0.7017
EarlyStopping counter: 2 out of 20
Epoch 17/1000, Train Loss: 0.6954, Val Loss: 0.7012
Validation loss decreased (0.702362 -> 0.701170). Saving model...
Epoch 18/1000, Train Loss: 0.6956, Val Loss: 0.7008
EarlyStopping counter: 1 out of 20
Epoch 19/1000, Train Loss: 0.6953, Val Loss: 0.7003
EarlyStopping counter: 2 out of 20
Epoch 20/1000, Train Loss: 0.6957, Val Loss: 0.7000
Validation loss decreased (0.701170 -> 0.699971). Saving model...
Epoch 21/1000, Train Loss: 0.6951, Val Loss: 0.6994
EarlyStopping counter: 1 out of 20
Epoch 22/1000, Train Loss: 0.6953, Val Loss: 0.6991
EarlyStopping counter: 2 out of 20
Epoch 23/1000, Train Loss: 0.6950, Val Loss: 0.6984
Validation loss decreased (0.699971 -> 0.698410). Saving model...
Epoch 24/1000, Train Loss: 0.6945, Val Loss: 0.6980
EarlyStopping counter: 1 out of 20
Epoch 25/1000, Train Loss: 0.6945, Val Loss: 0.6976
EarlyStopping counter: 2 out of 20
Epoch 26/1000, Train Loss: 0.6943, Val Loss: 0.6972
Validation loss decreased (0.698410 -> 0.697170). Saving model...
Epoch 27/1000, Train Loss: 0.6944, Val Loss: 0.6968
EarlyStopping counter: 1 out of 20
Epoch 28/1000, Train Loss: 0.6942, Val Loss: 0.6964
EarlyStopping counter: 2 out of 20
Epoch 29/1000, Train Loss: 0.6941, Val Loss: 0.6959
Validation loss decreased (0.697170 -> 0.695936). Saving model...
Epoch 30/1000, Train Loss: 0.6939, Val Loss: 0.6955
EarlyStopping counter: 1 out of 20
Epoch 31/1000, Train Loss: 0.6938, Val Loss: 0.6952
EarlyStopping counter: 2 out of 20
Epoch 32/1000, Train Loss: 0.6938, Val Loss: 0.6948
Validation loss decreased (0.695936 -> 0.694771). Saving model...
Epoch 33/1000, Train Loss: 0.6937, Val Loss: 0.6944
EarlyStopping counter: 1 out of 20
Epoch 34/1000, Train Loss: 0.6934, Val Loss: 0.6940
EarlyStopping counter: 2 out of 20
Epoch 35/1000, Train Loss: 0.6934, Val Loss: 0.6937
Validation loss decreased (0.694771 -> 0.693746). Saving model...
Epoch 36/1000, Train Loss: 0.6933, Val Loss: 0.6933
EarlyStopping counter: 1 out of 20
Epoch 37/1000, Train Loss: 0.6931, Val Loss: 0.6930
EarlyStopping counter: 2 out of 20
Epoch 38/1000, Train Loss: 0.6930, Val Loss: 0.6927
EarlyStopping counter: 3 out of 20
Epoch 39/1000, Train Loss: 0.6930, Val Loss: 0.6923
Validation loss decreased (0.693746 -> 0.692287). Saving model...
Epoch 40/1000, Train Loss: 0.6929, Val Loss: 0.6920
EarlyStopping counter: 1 out of 20
Epoch 41/1000, Train Loss: 0.6929, Val Loss: 0.6919
EarlyStopping counter: 2 out of 20
Epoch 42/1000, Train Loss: 0.6928, Val Loss: 0.6916
EarlyStopping counter: 3 out of 20
Epoch 43/1000, Train Loss: 0.6928, Val Loss: 0.6914
EarlyStopping counter: 4 out of 20
Epoch 44/1000, Train Loss: 0.6926, Val Loss: 0.6912
Validation loss decreased (0.692287 -> 0.691212). Saving model...
Epoch 45/1000, Train Loss: 0.6926, Val Loss: 0.6910
EarlyStopping counter: 1 out of 20
Epoch 46/1000, Train Loss: 0.6927, Val Loss: 0.6908
EarlyStopping counter: 2 out of 20
Epoch 47/1000, Train Loss: 0.6926, Val Loss: 0.6906
EarlyStopping counter: 3 out of 20
Epoch 48/1000, Train Loss: 0.6925, Val Loss: 0.6906
EarlyStopping counter: 4 out of 20
Epoch 49/1000, Train Loss: 0.6925, Val Loss: 0.6903
EarlyStopping counter: 5 out of 20
Epoch 50/1000, Train Loss: 0.6925, Val Loss: 0.6901
Validation loss decreased (0.691212 -> 0.690074). Saving model...
Epoch 51/1000, Train Loss: 0.6922, Val Loss: 0.6900
EarlyStopping counter: 1 out of 20
Epoch 52/1000, Train Loss: 0.6923, Val Loss: 0.6898
EarlyStopping counter: 2 out of 20
Epoch 53/1000, Train Loss: 0.6923, Val Loss: 0.6897
EarlyStopping counter: 3 out of 20
Epoch 54/1000, Train Loss: 0.6925, Val Loss: 0.6896
EarlyStopping counter: 4 out of 20
Epoch 55/1000, Train Loss: 0.6921, Val Loss: 0.6895
EarlyStopping counter: 5 out of 20
Epoch 56/1000, Train Loss: 0.6923, Val Loss: 0.6893
EarlyStopping counter: 6 out of 20
Epoch 57/1000, Train Loss: 0.6920, Val Loss: 0.6893
EarlyStopping counter: 7 out of 20
Epoch 58/1000, Train Loss: 0.6925, Val Loss: 0.6891
EarlyStopping counter: 8 out of 20
Epoch 59/1000, Train Loss: 0.6922, Val Loss: 0.6891
Validation loss decreased (0.690074 -> 0.689056). Saving model...
Epoch 60/1000, Train Loss: 0.6921, Val Loss: 0.6890
EarlyStopping counter: 1 out of 20
Epoch 61/1000, Train Loss: 0.6922, Val Loss: 0.6889
EarlyStopping counter: 2 out of 20
Epoch 62/1000, Train Loss: 0.6918, Val Loss: 0.6889
EarlyStopping counter: 3 out of 20
Epoch 63/1000, Train Loss: 0.6923, Val Loss: 0.6887
EarlyStopping counter: 4 out of 20
Epoch 64/1000, Train Loss: 0.6919, Val Loss: 0.6886
EarlyStopping counter: 5 out of 20
Epoch 65/1000, Train Loss: 0.6923, Val Loss: 0.6886
EarlyStopping counter: 6 out of 20
Epoch 66/1000, Train Loss: 0.6920, Val Loss: 0.6886
EarlyStopping counter: 7 out of 20
Epoch 67/1000, Train Loss: 0.6921, Val Loss: 0.6884
EarlyStopping counter: 8 out of 20
Epoch 68/1000, Train Loss: 0.6922, Val Loss: 0.6883
EarlyStopping counter: 9 out of 20
Epoch 69/1000, Train Loss: 0.6919, Val Loss: 0.6883
EarlyStopping counter: 10 out of 20
Epoch 70/1000, Train Loss: 0.6923, Val Loss: 0.6883
EarlyStopping counter: 11 out of 20
Epoch 71/1000, Train Loss: 0.6918, Val Loss: 0.6883
EarlyStopping counter: 12 out of 20
Epoch 72/1000, Train Loss: 0.6920, Val Loss: 0.6882
EarlyStopping counter: 13 out of 20
Epoch 73/1000, Train Loss: 0.6923, Val Loss: 0.6881
EarlyStopping counter: 14 out of 20
Epoch 74/1000, Train Loss: 0.6923, Val Loss: 0.6881
EarlyStopping counter: 15 out of 20
Epoch 75/1000, Train Loss: 0.6921, Val Loss: 0.6881
EarlyStopping counter: 16 out of 20
Epoch 76/1000, Train Loss: 0.6921, Val Loss: 0.6881
Validation loss decreased (0.689056 -> 0.688051). Saving model...
Epoch 77/1000, Train Loss: 0.6919, Val Loss: 0.6881
EarlyStopping counter: 1 out of 20
Epoch 78/1000, Train Loss: 0.6922, Val Loss: 0.6880
EarlyStopping counter: 2 out of 20
Epoch 79/1000, Train Loss: 0.6921, Val Loss: 0.6880
EarlyStopping counter: 3 out of 20
Epoch 80/1000, Train Loss: 0.6922, Val Loss: 0.6879
EarlyStopping counter: 4 out of 20
Epoch 81/1000, Train Loss: 0.6918, Val Loss: 0.6879
EarlyStopping counter: 5 out of 20
Epoch 82/1000, Train Loss: 0.6916, Val Loss: 0.6879
EarlyStopping counter: 6 out of 20
Epoch 83/1000, Train Loss: 0.6919, Val Loss: 0.6879
EarlyStopping counter: 7 out of 20
Epoch 84/1000, Train Loss: 0.6923, Val Loss: 0.6877
EarlyStopping counter: 8 out of 20
Epoch 85/1000, Train Loss: 0.6919, Val Loss: 0.6877
EarlyStopping counter: 9 out of 20
Epoch 86/1000, Train Loss: 0.6919, Val Loss: 0.6878
EarlyStopping counter: 10 out of 20
Epoch 87/1000, Train Loss: 0.6922, Val Loss: 0.6877
EarlyStopping counter: 11 out of 20
Epoch 88/1000, Train Loss: 0.6918, Val Loss: 0.6877
EarlyStopping counter: 12 out of 20
Epoch 89/1000, Train Loss: 0.6919, Val Loss: 0.6877
EarlyStopping counter: 13 out of 20
Epoch 90/1000, Train Loss: 0.6920, Val Loss: 0.6877
EarlyStopping counter: 14 out of 20
Epoch 91/1000, Train Loss: 0.6919, Val Loss: 0.6876
EarlyStopping counter: 15 out of 20
Epoch 92/1000, Train Loss: 0.6917, Val Loss: 0.6876
EarlyStopping counter: 16 out of 20
Epoch 93/1000, Train Loss: 0.6918, Val Loss: 0.6876
EarlyStopping counter: 17 out of 20
Epoch 94/1000, Train Loss: 0.6920, Val Loss: 0.6875
EarlyStopping counter: 18 out of 20
Epoch 95/1000, Train Loss: 0.6920, Val Loss: 0.6876
EarlyStopping counter: 19 out of 20
Epoch 96/1000, Train Loss: 0.6924, Val Loss: 0.6875
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 37, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 3, 'layer_size': 10, 'lr': 0.0005, 'l2_reg': 0.1, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.5}

In [24]:
def create_mlp_resnet(input_dim, output_dim, block_dim, hidden_dim, num_blocks, lr, l2_reg):
    model = ResNet(
        input_dim = input_dim,
        output_dim = output_dim,
        num_blocks = num_blocks,
        hidden_dim = hidden_dim,
        block_dim = block_dim
    )
    optimizer = optim.Adam(model.parameters(), lr, weight_decay=l2_reg)

    return model, optimizer

In [25]:
specified_configs = [
    # D block D hidden N blocks Learning rate L2 regularisation
    {'block_dim': 16, 'hidden_dim': 8, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.01},
    {'block_dim': 32, 'hidden_dim': 16, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.1},
    {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.01},
    {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.1},
]

for idx, params in enumerate(specified_configs):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    params.update({
    'input_dim': X_boot.shape[1],
    'output_dim': 1
})
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    X_boot_tensor = torch.FloatTensor(X_boot_scaled)
    y_boot_tensor = torch.FloatTensor(y_boot.values)
    train_dataset = TensorDataset(X_boot_tensor, y_boot_tensor)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    X_val_scaled = scaler.transform(X_val)
    X_val_tensor = torch.FloatTensor(X_val_scaled)
    y_val_tensor = torch.FloatTensor(y_val.values)
    val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
    val_loader = DataLoader(val_dataset, batch_size=32)

    model, optimizer = create_mlp_resnet(
        input_dim = params['input_dim'], 
        output_dim = params['output_dim'],
        num_blocks=params['num_blocks'],
        hidden_dim=params['hidden_dim'],
        block_dim=params['block_dim'],
        lr=params['lr'],
        l2_reg=params['l2_reg'])


    early_stopping = EarlyStopping(patience=20, min_delta=0.001, verbose=True)
    criterion = nn.BCEWithLogitsLoss()
  
    train_losses = []
    val_losses = []
    
    for epoch in range(1000):
        # Training phase
        model.train()
        train_loss = 0.0
        for batch_idx, (data, target) in enumerate(train_loader):
            
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output.squeeze(), target)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        avg_train_loss = train_loss / len(train_loader)
        train_losses.append(avg_train_loss)
        
        # Validation phase
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for data, target in val_loader:
                output = model(data)
                val_loss += criterion(output.squeeze(), target).item()
        
        avg_val_loss = val_loss / len(val_loader)
        val_losses.append(avg_val_loss)
        
        print(f'Epoch {epoch+1}/{1000}, '
                f'Train Loss: {avg_train_loss:.4f}, '
                f'Val Loss: {avg_val_loss:.4f}')
        
        # Early stopping check
        if early_stopping(avg_val_loss, model):
            print("Early stopping triggered. Restoring best model...")
            # Restore the best model
            model.load_state_dict(early_stopping.best_model_state)
            break
    
    model.eval()

    all_predictions = []
    all_targets = []

    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(val_loader):
            predictions = model(data)
            
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(target.numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions, axis=0)
    all_targets = np.concatenate(all_targets, axis=0)

    # Calculate RMSE
    roc = float(roc_auc_score(all_targets, all_predictions))
    
    # Store metadata
    model_metadata = {
        'index': config_id,
        'model_type': 'ResNet',
        'hyperparams': params,
        'roc': roc
    }
    config_id += 1
    print(model_metadata)
    models_list.append(model_metadata)

Epoch 1/1000, Train Loss: 0.5132, Val Loss: 0.5996
Validation loss decreased (inf -> 0.599579). Saving model...
Epoch 2/1000, Train Loss: 0.3592, Val Loss: 0.6065
EarlyStopping counter: 1 out of 20
Epoch 3/1000, Train Loss: 0.3690, Val Loss: 0.5763
Validation loss decreased (0.599579 -> 0.576321). Saving model...
Epoch 4/1000, Train Loss: 0.3310, Val Loss: 0.6183
EarlyStopping counter: 1 out of 20
Epoch 5/1000, Train Loss: 0.2822, Val Loss: 0.5865
EarlyStopping counter: 2 out of 20
Epoch 6/1000, Train Loss: 0.2847, Val Loss: 0.7087
EarlyStopping counter: 3 out of 20
Epoch 7/1000, Train Loss: 0.2735, Val Loss: 0.6281
EarlyStopping counter: 4 out of 20
Epoch 8/1000, Train Loss: 0.2707, Val Loss: 0.6155
EarlyStopping counter: 5 out of 20
Epoch 9/1000, Train Loss: 0.2373, Val Loss: 0.7189
EarlyStopping counter: 6 out of 20
Epoch 10/1000, Train Loss: 0.2409, Val Loss: 0.7293
EarlyStopping counter: 7 out of 20
Epoch 11/1000, Train Loss: 0.2788, Val Loss: 0.6455
EarlyStopping counter: 8 out of 20
Epoch 12/1000, Train Loss: 0.2405, Val Loss: 0.6604
EarlyStopping counter: 9 out of 20
Epoch 13/1000, Train Loss: 0.2255, Val Loss: 0.8280
EarlyStopping counter: 10 out of 20
Epoch 14/1000, Train Loss: 0.2591, Val Loss: 0.7240
EarlyStopping counter: 11 out of 20
Epoch 15/1000, Train Loss: 0.2512, Val Loss: 0.7506
EarlyStopping counter: 12 out of 20
Epoch 16/1000, Train Loss: 0.2603, Val Loss: 0.7184
EarlyStopping counter: 13 out of 20
Epoch 17/1000, Train Loss: 0.2660, Val Loss: 0.7465
EarlyStopping counter: 14 out of 20
Epoch 18/1000, Train Loss: 0.2297, Val Loss: 0.7160
EarlyStopping counter: 15 out of 20
Epoch 19/1000, Train Loss: 0.2311, Val Loss: 0.7879
EarlyStopping counter: 16 out of 20
Epoch 20/1000, Train Loss: 0.2432, Val Loss: 0.6673
EarlyStopping counter: 17 out of 20
Epoch 21/1000, Train Loss: 0.2341, Val Loss: 0.7861
EarlyStopping counter: 18 out of 20
Epoch 22/1000, Train Loss: 0.2032, Val Loss: 0.7041
EarlyStopping counter: 19 out of 20
Epoch 23/1000, Train Loss: 0.2427, Val Loss: 0.7454
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 38, 'model_type': 'ResNet', 'hyperparams': {'block_dim': 16, 'hidden_dim': 8, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.01, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.8057124921531701}
Epoch 1/1000, Train Loss: 0.5156, Val Loss: 0.5816
Validation loss decreased (inf -> 0.581578). Saving model...
Epoch 2/1000, Train Loss: 0.4695, Val Loss: 0.5540
Validation loss decreased (0.581578 -> 0.554000). Saving model...
Epoch 3/1000, Train Loss: 0.4677, Val Loss: 0.5700
EarlyStopping counter: 1 out of 20
Epoch 4/1000, Train Loss: 0.4534, Val Loss: 0.5629
EarlyStopping counter: 2 out of 20
Epoch 5/1000, Train Loss: 0.4404, Val Loss: 0.5966
EarlyStopping counter: 3 out of 20
Epoch 6/1000, Train Loss: 0.4538, Val Loss: 0.6056
EarlyStopping counter: 4 out of 20
Epoch 7/1000, Train Loss: 0.4592, Val Loss: 0.6060
EarlyStopping counter: 5 out of 20
Epoch 8/1000, Train Loss: 0.4340, Val Loss: 0.6450
EarlyStopping counter: 6 out of 20
Epoch 9/1000, Train Loss: 0.4398, Val Loss: 0.6165
EarlyStopping counter: 7 out of 20
Epoch 10/1000, Train Loss: 0.4379, Val Loss: 0.5997
EarlyStopping counter: 8 out of 20
Epoch 11/1000, Train Loss: 0.4105, Val Loss: 0.5618
EarlyStopping counter: 9 out of 20
Epoch 12/1000, Train Loss: 0.4355, Val Loss: 0.5764
EarlyStopping counter: 10 out of 20
Epoch 13/1000, Train Loss: 0.4298, Val Loss: 0.6734
EarlyStopping counter: 11 out of 20
Epoch 14/1000, Train Loss: 0.4284, Val Loss: 0.6144
EarlyStopping counter: 12 out of 20
Epoch 15/1000, Train Loss: 0.4167, Val Loss: 0.5900
EarlyStopping counter: 13 out of 20
Epoch 16/1000, Train Loss: 0.4321, Val Loss: 0.5756
EarlyStopping counter: 14 out of 20
Epoch 17/1000, Train Loss: 0.4310, Val Loss: 0.6443
EarlyStopping counter: 15 out of 20
Epoch 18/1000, Train Loss: 0.4150, Val Loss: 0.5942
EarlyStopping counter: 16 out of 20
Epoch 19/1000, Train Loss: 0.4408, Val Loss: 0.5502
Validation loss decreased (0.554000 -> 0.550152). Saving model...
Epoch 20/1000, Train Loss: 0.4339, Val Loss: 0.5692
EarlyStopping counter: 1 out of 20
Epoch 21/1000, Train Loss: 0.4194, Val Loss: 0.5655
EarlyStopping counter: 2 out of 20
Epoch 22/1000, Train Loss: 0.4015, Val Loss: 0.5598
EarlyStopping counter: 3 out of 20
Epoch 23/1000, Train Loss: 0.4250, Val Loss: 0.6090
EarlyStopping counter: 4 out of 20
Epoch 24/1000, Train Loss: 0.4500, Val Loss: 0.5937
EarlyStopping counter: 5 out of 20
Epoch 25/1000, Train Loss: 0.4260, Val Loss: 0.6371
EarlyStopping counter: 6 out of 20
Epoch 26/1000, Train Loss: 0.4167, Val Loss: 0.5363
Validation loss decreased (0.550152 -> 0.536347). Saving model...
Epoch 27/1000, Train Loss: 0.3943, Val Loss: 0.7035
EarlyStopping counter: 1 out of 20
Epoch 28/1000, Train Loss: 0.4039, Val Loss: 0.5305
Validation loss decreased (0.536347 -> 0.530468). Saving model...
Epoch 29/1000, Train Loss: 0.4006, Val Loss: 0.5856
EarlyStopping counter: 1 out of 20
Epoch 30/1000, Train Loss: 0.4067, Val Loss: 0.5580
EarlyStopping counter: 2 out of 20
Epoch 31/1000, Train Loss: 0.3881, Val Loss: 0.5651
EarlyStopping counter: 3 out of 20
Epoch 32/1000, Train Loss: 0.4103, Val Loss: 0.5761
EarlyStopping counter: 4 out of 20
Epoch 33/1000, Train Loss: 0.4120, Val Loss: 0.5701
EarlyStopping counter: 5 out of 20
Epoch 34/1000, Train Loss: 0.3956, Val Loss: 0.6142
EarlyStopping counter: 6 out of 20
Epoch 35/1000, Train Loss: 0.4280, Val Loss: 0.5703
EarlyStopping counter: 7 out of 20
Epoch 36/1000, Train Loss: 0.4318, Val Loss: 0.6688
EarlyStopping counter: 8 out of 20
Epoch 37/1000, Train Loss: 0.4284, Val Loss: 0.5742
EarlyStopping counter: 9 out of 20
Epoch 38/1000, Train Loss: 0.4084, Val Loss: 0.5433
EarlyStopping counter: 10 out of 20
Epoch 39/1000, Train Loss: 0.4111, Val Loss: 0.5482
EarlyStopping counter: 11 out of 20
Epoch 40/1000, Train Loss: 0.4284, Val Loss: 0.5783
EarlyStopping counter: 12 out of 20
Epoch 41/1000, Train Loss: 0.4094, Val Loss: 0.5424
EarlyStopping counter: 13 out of 20
Epoch 42/1000, Train Loss: 0.4248, Val Loss: 0.6260
EarlyStopping counter: 14 out of 20
Epoch 43/1000, Train Loss: 0.4126, Val Loss: 0.5690
EarlyStopping counter: 15 out of 20
Epoch 44/1000, Train Loss: 0.4154, Val Loss: 0.5436
EarlyStopping counter: 16 out of 20
Epoch 45/1000, Train Loss: 0.4119, Val Loss: 0.6053
EarlyStopping counter: 17 out of 20
Epoch 46/1000, Train Loss: 0.3997, Val Loss: 0.5877
EarlyStopping counter: 18 out of 20
Epoch 47/1000, Train Loss: 0.4389, Val Loss: 0.5866
EarlyStopping counter: 19 out of 20
Epoch 48/1000, Train Loss: 0.4032, Val Loss: 0.5976
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 39, 'model_type': 'ResNet', 'hyperparams': {'block_dim': 32, 'hidden_dim': 16, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.1, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.7945027351807012}
Epoch 1/1000, Train Loss: 0.5757, Val Loss: 0.5484
Validation loss decreased (inf -> 0.548367). Saving model...
Epoch 2/1000, Train Loss: 0.4334, Val Loss: 0.5630
EarlyStopping counter: 1 out of 20
Epoch 3/1000, Train Loss: 0.3725, Val Loss: 0.5953
EarlyStopping counter: 2 out of 20
Epoch 4/1000, Train Loss: 0.3373, Val Loss: 0.5997
EarlyStopping counter: 3 out of 20
Epoch 5/1000, Train Loss: 0.3068, Val Loss: 0.6840
EarlyStopping counter: 4 out of 20
Epoch 6/1000, Train Loss: 0.3195, Val Loss: 0.6246
EarlyStopping counter: 5 out of 20
Epoch 7/1000, Train Loss: 0.2548, Val Loss: 0.6417
EarlyStopping counter: 6 out of 20
Epoch 8/1000, Train Loss: 0.2440, Val Loss: 0.6761
EarlyStopping counter: 7 out of 20
Epoch 9/1000, Train Loss: 0.2129, Val Loss: 0.7351
EarlyStopping counter: 8 out of 20
Epoch 10/1000, Train Loss: 0.1936, Val Loss: 0.7241
EarlyStopping counter: 9 out of 20
Epoch 11/1000, Train Loss: 0.1761, Val Loss: 0.7547
EarlyStopping counter: 10 out of 20
Epoch 12/1000, Train Loss: 0.1895, Val Loss: 0.7015
EarlyStopping counter: 11 out of 20
Epoch 13/1000, Train Loss: 0.1687, Val Loss: 0.7169
EarlyStopping counter: 12 out of 20
Epoch 14/1000, Train Loss: 0.1553, Val Loss: 0.8251
EarlyStopping counter: 13 out of 20
Epoch 15/1000, Train Loss: 0.1463, Val Loss: 0.7972
EarlyStopping counter: 14 out of 20
Epoch 16/1000, Train Loss: 0.1530, Val Loss: 0.8149
EarlyStopping counter: 15 out of 20
Epoch 17/1000, Train Loss: 0.1198, Val Loss: 0.8470
EarlyStopping counter: 16 out of 20
Epoch 18/1000, Train Loss: 0.1356, Val Loss: 0.9301
EarlyStopping counter: 17 out of 20
Epoch 19/1000, Train Loss: 0.1323, Val Loss: 0.8884
EarlyStopping counter: 18 out of 20
Epoch 20/1000, Train Loss: 0.1244, Val Loss: 0.8926
EarlyStopping counter: 19 out of 20
Epoch 21/1000, Train Loss: 0.1131, Val Loss: 0.8852
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 40, 'model_type': 'ResNet', 'hyperparams': {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.01, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.7689444892834723}
Epoch 1/1000, Train Loss: 0.5920, Val Loss: 0.5712
Validation loss decreased (inf -> 0.571205). Saving model...
Epoch 2/1000, Train Loss: 0.4948, Val Loss: 0.5524
Validation loss decreased (0.571205 -> 0.552351). Saving model...
Epoch 3/1000, Train Loss: 0.4772, Val Loss: 0.5345
Validation loss decreased (0.552351 -> 0.534534). Saving model...
Epoch 4/1000, Train Loss: 0.4564, Val Loss: 0.5519
EarlyStopping counter: 1 out of 20
Epoch 5/1000, Train Loss: 0.4387, Val Loss: 0.5301
Validation loss decreased (0.534534 -> 0.530099). Saving model...
Epoch 6/1000, Train Loss: 0.4266, Val Loss: 0.5300
EarlyStopping counter: 1 out of 20
Epoch 7/1000, Train Loss: 0.4231, Val Loss: 0.5350
EarlyStopping counter: 2 out of 20
Epoch 8/1000, Train Loss: 0.4130, Val Loss: 0.5277
Validation loss decreased (0.530099 -> 0.527715). Saving model...
Epoch 9/1000, Train Loss: 0.4201, Val Loss: 0.5337
EarlyStopping counter: 1 out of 20
Epoch 10/1000, Train Loss: 0.4111, Val Loss: 0.5394
EarlyStopping counter: 2 out of 20
Epoch 11/1000, Train Loss: 0.3992, Val Loss: 0.5266
Validation loss decreased (0.527715 -> 0.526619). Saving model...
Epoch 12/1000, Train Loss: 0.4113, Val Loss: 0.5471
EarlyStopping counter: 1 out of 20
Epoch 13/1000, Train Loss: 0.4020, Val Loss: 0.5346
EarlyStopping counter: 2 out of 20
Epoch 14/1000, Train Loss: 0.4116, Val Loss: 0.5298
EarlyStopping counter: 3 out of 20
Epoch 15/1000, Train Loss: 0.3930, Val Loss: 0.5217
Validation loss decreased (0.526619 -> 0.521749). Saving model...
Epoch 16/1000, Train Loss: 0.3951, Val Loss: 0.5233
EarlyStopping counter: 1 out of 20
Epoch 17/1000, Train Loss: 0.3994, Val Loss: 0.5468
EarlyStopping counter: 2 out of 20
Epoch 18/1000, Train Loss: 0.3991, Val Loss: 0.5272
EarlyStopping counter: 3 out of 20
Epoch 19/1000, Train Loss: 0.3994, Val Loss: 0.5351
EarlyStopping counter: 4 out of 20
Epoch 20/1000, Train Loss: 0.4022, Val Loss: 0.5546
EarlyStopping counter: 5 out of 20
Epoch 21/1000, Train Loss: 0.3989, Val Loss: 0.5178
Validation loss decreased (0.521749 -> 0.517758). Saving model...
Epoch 22/1000, Train Loss: 0.3870, Val Loss: 0.5247
EarlyStopping counter: 1 out of 20
Epoch 23/1000, Train Loss: 0.3869, Val Loss: 0.5093
Validation loss decreased (0.517758 -> 0.509335). Saving model...
Epoch 24/1000, Train Loss: 0.3879, Val Loss: 0.5231
EarlyStopping counter: 1 out of 20
Epoch 25/1000, Train Loss: 0.3925, Val Loss: 0.5158
EarlyStopping counter: 2 out of 20
Epoch 26/1000, Train Loss: 0.3886, Val Loss: 0.5359
EarlyStopping counter: 3 out of 20
Epoch 27/1000, Train Loss: 0.3794, Val Loss: 0.5113
EarlyStopping counter: 4 out of 20
Epoch 28/1000, Train Loss: 0.3778, Val Loss: 0.5210
EarlyStopping counter: 5 out of 20
Epoch 29/1000, Train Loss: 0.3789, Val Loss: 0.5188
EarlyStopping counter: 6 out of 20
Epoch 30/1000, Train Loss: 0.3812, Val Loss: 0.5156
EarlyStopping counter: 7 out of 20
Epoch 31/1000, Train Loss: 0.3720, Val Loss: 0.5265
EarlyStopping counter: 8 out of 20
Epoch 32/1000, Train Loss: 0.3808, Val Loss: 0.5255
EarlyStopping counter: 9 out of 20
Epoch 33/1000, Train Loss: 0.3788, Val Loss: 0.5189
EarlyStopping counter: 10 out of 20
Epoch 34/1000, Train Loss: 0.3816, Val Loss: 0.5408
EarlyStopping counter: 11 out of 20
Epoch 35/1000, Train Loss: 0.3794, Val Loss: 0.5233
EarlyStopping counter: 12 out of 20
Epoch 36/1000, Train Loss: 0.3803, Val Loss: 0.5224
EarlyStopping counter: 13 out of 20
Epoch 37/1000, Train Loss: 0.3716, Val Loss: 0.5227
EarlyStopping counter: 14 out of 20
Epoch 38/1000, Train Loss: 0.3773, Val Loss: 0.5319
EarlyStopping counter: 15 out of 20
Epoch 39/1000, Train Loss: 0.3852, Val Loss: 0.5122
EarlyStopping counter: 16 out of 20
Epoch 40/1000, Train Loss: 0.3782, Val Loss: 0.5269
EarlyStopping counter: 17 out of 20
Epoch 41/1000, Train Loss: 0.3747, Val Loss: 0.5180
EarlyStopping counter: 18 out of 20
Epoch 42/1000, Train Loss: 0.3721, Val Loss: 0.5161
EarlyStopping counter: 19 out of 20
Epoch 43/1000, Train Loss: 0.3770, Val Loss: 0.5183
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 41, 'model_type': 'ResNet', 'hyperparams': {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.1, 'input_dim': 517, 'output_dim': 1}, 'roc': 0.8159806295399515}

In [26]:
models_df = pd.DataFrame(columns=[
    'index', 'model_type', 'hyperparams', 'roc'
])
models_df = pd.DataFrame(models_list)
models_df = models_df.sort_values('roc', ascending=False).reset_index(drop=True)
final_models = models_df.head(10)
final_models

,index,model_type,hyperparams,roc
0,41,ResNet,"{'block_dim': 64, 'hidden_dim': 32, 'num_block...",0.815981
1,35,MLP_PyTorch,"{'n_layers': 2, 'layer_size': 10, 'lr': 0.001,...",0.807237
2,38,ResNet,"{'block_dim': 16, 'hidden_dim': 8, 'num_blocks...",0.805712
3,39,ResNet,"{'block_dim': 32, 'hidden_dim': 16, 'num_block...",0.794503
4,34,MLP_PyTorch,"{'n_layers': 2, 'layer_size': 5, 'lr': 0.01, '...",0.772958
5,40,ResNet,"{'block_dim': 64, 'hidden_dim': 32, 'num_block...",0.768944
6,0,KNeighborsClassifier,{},0.767353
7,22,XGBClassifier,"{'max_depth': 10, 'n_estimators': 100, 'learni...",0.756524
8,2,KNeighborsClassifier,{},0.755448
9,36,MLP_PyTorch,"{'n_layers': 3, 'layer_size': 10, 'lr': 0.001,...",0.749350

In [27]:
def softmax(series):
    exp_x = np.exp(series - series.max())
    return exp_x / exp_x.sum()

In [28]:
final_models['weights'] = softmax(final_models['roc'])
final_models

/tmp/ipykernel_388791/4123806128.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_models['weights'] = softmax(final_models['roc'])

,index,model_type,hyperparams,roc,weights
0,41,ResNet,"{'block_dim': 64, 'hidden_dim': 32, 'num_block...",0.815981,0.103698
1,35,MLP_PyTorch,"{'n_layers': 2, 'layer_size': 10, 'lr': 0.001,...",0.807237,0.102795
2,38,ResNet,"{'block_dim': 16, 'hidden_dim': 8, 'num_blocks...",0.805712,0.102639
3,39,ResNet,"{'block_dim': 32, 'hidden_dim': 16, 'num_block...",0.794503,0.101495
4,34,MLP_PyTorch,"{'n_layers': 2, 'layer_size': 5, 'lr': 0.01, '...",0.772958,0.099331
5,40,ResNet,"{'block_dim': 64, 'hidden_dim': 32, 'num_block...",0.768944,0.098933
6,0,KNeighborsClassifier,{},0.767353,0.098776
7,22,XGBClassifier,"{'max_depth': 10, 'n_estimators': 100, 'learni...",0.756524,0.097712
8,2,KNeighborsClassifier,{},0.755448,0.097607
9,36,MLP_PyTorch,"{'n_layers': 3, 'layer_size': 10, 'lr': 0.001,...",0.749350,0.097014

In [29]:
roc = sum(final_models['roc']*final_models['weights'])
roc

0.7799356352959933