In [1]:
import numpy as np
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.model_selection import train_test_split, ParameterGrid
from sklearn.utils import resample
from sklearn.metrics import root_mean_squared_error
from sklearn.neighbors import KNeighborsRegressor
from sklearn.linear_model import Lasso, Ridge
from sklearn.kernel_ridge import KernelRidge
from sklearn.ensemble import RandomForestRegressor
from xgboost import XGBRegressor
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, ConstantKernel as C, RBF, RationalQuadratic
import time
import torch
from torch.utils.data import DataLoader, TensorDataset
from src.models.mlp import MLP, create_mlp_pytorch, EarlyStopping
from src.models.resnet import ResBlock, ResNet
import torch.optim as optim

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/xgboost/core.py:377: FutureWarning: Your system has an old version of glibc (< 2.28). We will stop supporting Linux distros with glibc older than 2.28 after **May 31, 2025**. Please upgrade to a recent Linux distro (with glibc >= 2.28) to use future versions of XGBoost.
Note: You have installed the 'manylinux2014' variant of XGBoost. Certain features such as GPU algorithms or federated learning are not available. To use these features, please upgrade to a recent Linux distro with glibc 2.28+, and install the 'manylinux_2_28' variant.
  warnings.warn(
No normalization for SPS. Feature removed!
No normalization for AvgIpc. Feature removed!
No normalization for NumAmideBonds. Feature removed!
No normalization for NumAtomStereoCenters. Feature removed!
No normalization for NumBridgeheadAtoms. Feature removed!
No normalization for NumHeterocycles. Feature removed!
No normalization for NumSpiroAtoms. Feature removed!
No normalization for NumUnspecifiedAtomStereoCenters. Feature removed!
No normalization for Phi. Feature removed!
Skipped loading some Tensorflow models, missing a dependency. No module named 'tensorflow'
Skipped loading modules with pytorch-geometric dependency, missing a dependency. No module named 'torch_geometric'
Skipped loading modules with transformers dependency. No module named 'transformers'
cannot import name 'HuggingFaceModel' from 'deepchem.models.torch_models' (/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading modules with pytorch-geometric dependency, missing a dependency. cannot import name 'DMPNN' from 'deepchem.models.torch_models' (/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/deepchem/models/torch_models/__init__.py)
Skipped loading some Jax models, missing a dependency. No module named 'jax'
Skipped loading some PyTorch models, missing a dependency. No module named 'tensorflow'

In [2]:
descriptor_df = pd.read_csv('data/freesolv/external_descriptors.csv')
smiles_df = pd.read_csv('data/freesolv/smiles.csv')
learned_descriptors_df = pd.read_csv('data/freesolv/learned_predictors_0.csv')
df = pd.concat([learned_descriptors_df, descriptor_df, smiles_df], axis=1)

In [3]:
df.head()

,fp_0,fp_1,fp_2,fp_3,fp_4,fp_5,fp_6,fp_7,fp_8,fp_9,...,209,210,211,212,213,214,215,y,w,ids
0,0.005919,0.0,0.000000,0.0,0.0,0.0,0.0,0.009849,0.030713,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.107729,1.0,C(CCl)OCCCl
1,0.016760,0.0,0.004031,0.0,0.0,0.0,0.0,0.002265,0.022694,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.014446,1.0,C(Cl)(Cl)(Cl)Cl
2,0.006240,0.0,0.010199,0.0,0.0,0.0,0.0,0.007726,0.026535,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.199502,1.0,CC(C)CC(=O)C
3,0.007206,0.0,0.005383,0.0,0.0,0.0,0.0,0.005392,0.038531,0.0,...,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.449453,1.0,CCCCO[N+](=O)[O-]
4,0.003805,0.0,0.006889,0.0,0.0,0.0,0.0,0.004972,0.007662,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.574428,1.0,CSC

In [4]:
df = df.drop(columns='ids')
df.head()

,fp_0,fp_1,fp_2,fp_3,fp_4,fp_5,fp_6,fp_7,fp_8,fp_9,...,208,209,210,211,212,213,214,215,y,w
0,0.005919,0.0,0.000000,0.0,0.0,0.0,0.0,0.009849,0.030713,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.107729,1.0
1,0.016760,0.0,0.004031,0.0,0.0,0.0,0.0,0.002265,0.022694,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.014446,1.0
2,0.006240,0.0,0.010199,0.0,0.0,0.0,0.0,0.007726,0.026535,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.199502,1.0
3,0.007206,0.0,0.005383,0.0,0.0,0.0,0.0,0.005392,0.038531,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.449453,1.0
4,0.003805,0.0,0.006889,0.0,0.0,0.0,0.0,0.004972,0.007662,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.574428,1.0

In [5]:
df['w'].unique()

array([1.])

In [6]:
df = df.drop(columns='w')
df.head()

,fp_0,fp_1,fp_2,fp_3,fp_4,fp_5,fp_6,fp_7,fp_8,fp_9,...,207,208,209,210,211,212,213,214,215,y
0,0.005919,0.0,0.000000,0.0,0.0,0.0,0.0,0.009849,0.030713,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,-0.107729
1,0.016760,0.0,0.004031,0.0,0.0,0.0,0.0,0.002265,0.022694,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.014446
2,0.006240,0.0,0.010199,0.0,0.0,0.0,0.0,0.007726,0.026535,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.199502
3,0.007206,0.0,0.005383,0.0,0.0,0.0,0.0,0.005392,0.038531,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,1.0,0.0,0.449453
4,0.003805,0.0,0.006889,0.0,0.0,0.0,0.0,0.004972,0.007662,0.0,...,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.0,0.574428

In [7]:
X = df.drop(columns=['y'])
y = df['y']

In [8]:
X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.2)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5)

In [9]:
models_df = pd.DataFrame(columns=[
    'index', 'model_type', 'hyperparams', 'rmse'
])
models_list = []
config_id = 0
base_seed = 42

In [10]:
for i in range(4):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = KNeighborsRegressor()
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': {},
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 0, 'model_type': 'KNeighborsRegressor', 'hyperparams': {}, 'rmse': 0.30109799755193034}
{'index': 1, 'model_type': 'KNeighborsRegressor', 'hyperparams': {}, 'rmse': 0.4657266303774585}
{'index': 2, 'model_type': 'KNeighborsRegressor', 'hyperparams': {}, 'rmse': 0.4090489627021739}
{'index': 3, 'model_type': 'KNeighborsRegressor', 'hyperparams': {}, 'rmse': 0.33176904431885146}

In [11]:
param_grid = {
    'alpha': [0.001, 0.002, 0.005, 0.01, 0.02, 0.05, 0.1, 0.2]
}

for params in ParameterGrid(param_grid):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = Lasso(**params)
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 4, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.001}, 'rmse': 0.26280552998679335}
{'index': 5, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.002}, 'rmse': 0.25729733201674054}
{'index': 6, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.005}, 'rmse': 0.29671325918853586}
{'index': 7, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.01}, 'rmse': 0.26053927565601315}
{'index': 8, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.02}, 'rmse': 0.28471073997471036}
{'index': 9, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.05}, 'rmse': 0.34324741130191005}
{'index': 10, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.1}, 'rmse': 0.3774793261411331}
{'index': 11, 'model_type': 'Lasso', 'hyperparams': {'alpha': 0.2}, 'rmse': 0.5313726916801317}

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 2.903e-01, tolerance: 5.046e-02
  model = cd_fast.enet_coordinate_descent(
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/linear_model/_coordinate_descent.py:695: ConvergenceWarning: Objective did not converge. You might want to increase the number of iterations, check the scale of the features or consider increasing regularisation. Duality gap: 1.095e-01, tolerance: 5.149e-02
  model = cd_fast.enet_coordinate_descent(

In [12]:
param_grid = {
    'alpha': [1, 2, 3, 5, 7, 10, 15, 20, 30, 50]
}

for params in ParameterGrid(param_grid):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = Ridge(**params)
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 12, 'model_type': 'Ridge', 'hyperparams': {'alpha': 1}, 'rmse': 0.274791406275937}
{'index': 13, 'model_type': 'Ridge', 'hyperparams': {'alpha': 2}, 'rmse': 0.2667811078874242}
{'index': 14, 'model_type': 'Ridge', 'hyperparams': {'alpha': 3}, 'rmse': 0.32722851294618766}
{'index': 15, 'model_type': 'Ridge', 'hyperparams': {'alpha': 5}, 'rmse': 0.27431612464288047}
{'index': 16, 'model_type': 'Ridge', 'hyperparams': {'alpha': 7}, 'rmse': 0.2583906647995346}
{'index': 17, 'model_type': 'Ridge', 'hyperparams': {'alpha': 10}, 'rmse': 0.2653915182964347}
{'index': 18, 'model_type': 'Ridge', 'hyperparams': {'alpha': 15}, 'rmse': 0.3008588245844687}
{'index': 19, 'model_type': 'Ridge', 'hyperparams': {'alpha': 20}, 'rmse': 0.2622551851519705}
{'index': 20, 'model_type': 'Ridge', 'hyperparams': {'alpha': 30}, 'rmse': 0.8964576365455814}
{'index': 21, 'model_type': 'Ridge', 'hyperparams': {'alpha': 50}, 'rmse': 0.7918415432135305}

In [13]:
param_grid = [
    # Polynomial kernel (3rd degree)
    {
        'kernel': ['poly'],
        'alpha': [0.1, 1, 10],
        'degree': [3],
    },
    # RBF kernel
    {
        'kernel': ['rbf'],
        'alpha': [0.1, 1, 10],
    }
]

for idx, params in enumerate(ParameterGrid(param_grid)):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = KernelRidge(**params)
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 22, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 0.1, 'degree': 3, 'kernel': 'poly'}, 'rmse': 0.30413401701908416}
{'index': 23, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 1, 'degree': 3, 'kernel': 'poly'}, 'rmse': 0.38796143986421605}
{'index': 24, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 10, 'degree': 3, 'kernel': 'poly'}, 'rmse': 0.8359538667074695}
{'index': 25, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 0.1, 'kernel': 'rbf'}, 'rmse': 0.35591709148388817}
{'index': 26, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 1, 'kernel': 'rbf'}, 'rmse': 0.4369372938666854}
{'index': 27, 'model_type': 'KernelRidge', 'hyperparams': {'alpha': 10, 'kernel': 'rbf'}, 'rmse': 0.6477949048304251}

In [14]:
param_grid = [
    {'max_depth': [3], 'n_estimators': [10]},
    {'max_depth': [5], 'n_estimators': [10]},
    {'max_depth': [5], 'n_estimators': [20]},
    {'max_depth': [5], 'n_estimators': [50]},
    {'max_depth': [8], 'n_estimators': [50]},
    {'max_depth': [8], 'n_estimators': [100]},
    {'max_depth': [5], 'n_estimators': [100]},
    {'max_depth': [8], 'n_estimators': [100]},
    {'max_depth': [16], 'n_estimators': [200]},
    {'max_depth': [32], 'n_estimators': [1000]}
]
for idx, params in enumerate(ParameterGrid(param_grid)):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    model = RandomForestRegressor(**params)
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)

    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

{'index': 28, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 3, 'n_estimators': 10}, 'rmse': 0.48316045829267057}
{'index': 29, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 10}, 'rmse': 0.36481943858227034}
{'index': 30, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 20}, 'rmse': 0.2897772097917187}
{'index': 31, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 50}, 'rmse': 0.31424632353868553}
{'index': 32, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 8, 'n_estimators': 50}, 'rmse': 0.26891537521403913}
{'index': 33, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 8, 'n_estimators': 100}, 'rmse': 0.3050162246606871}
{'index': 34, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 100}, 'rmse': 0.45434734706834556}
{'index': 35, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 8, 'n_estimators': 100}, 'rmse': 0.2753702275867707}
{'index': 36, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 16, 'n_estimators': 200}, 'rmse': 0.2782184113889237}
{'index': 37, 'model_type': 'RandomForestRegressor', 'hyperparams': {'max_depth': 32, 'n_estimators': 1000}, 'rmse': 0.23253547298298005}

In [15]:
hyperparams_list = [
    {'max_depth': 3, 'n_estimators': 100, 'learning_rate': 0.1},
    {'max_depth': 5, 'n_estimators': 100, 'learning_rate': 0.1},
    {'max_depth': 3, 'n_estimators': 200, 'learning_rate': 0.1},
    {'max_depth': 10, 'n_estimators': 200, 'learning_rate': 0.2},
    {'max_depth': 5, 'n_estimators': 500, 'learning_rate': 0.1},
    {'max_depth': 10, 'n_estimators': 500, 'learning_rate': 0.01},
    {'max_depth': 10, 'n_estimators': 1000, 'learning_rate': 0.1},
    {'max_depth': 32, 'n_estimators': 2000, 'learning_rate': 0.1}
]

for idx, params in enumerate(hyperparams_list):

    seed = base_seed + config_id

    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)

    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)

    start_time = time.time()
    model = XGBRegressor(
        max_depth=params['max_depth'],
        n_estimators=params['n_estimators'],
        learning_rate=params['learning_rate'],
        n_jobs=-1,
    )

    model.fit(X_boot_scaled, y_boot)

    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    
    rmse = root_mean_squared_error(y_val, y_val_pred)
    training_time = time.time() - start_time
    
    print(f'Training time: {training_time}')
    
    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    
    config_id += 1
    
    print(model_metadata)
    
    models_list.append(model_metadata)

Training time: 0.17751383781433105
{'index': 38, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 3, 'n_estimators': 100, 'learning_rate': 0.1}, 'rmse': 0.3173875292248438}
Training time: 0.2584071159362793
{'index': 39, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 100, 'learning_rate': 0.1}, 'rmse': 0.232863508655864}
Training time: 0.22453999519348145
{'index': 40, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 3, 'n_estimators': 200, 'learning_rate': 0.1}, 'rmse': 0.30695122712655953}
Training time: 0.5219578742980957
{'index': 41, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 10, 'n_estimators': 200, 'learning_rate': 0.2}, 'rmse': 0.3395619987867347}
Training time: 0.8248302936553955
{'index': 42, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 5, 'n_estimators': 500, 'learning_rate': 0.1}, 'rmse': 0.3636496691367162}
Training time: 5.013906002044678
{'index': 43, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 10, 'n_estimators': 500, 'learning_rate': 0.01}, 'rmse': 0.2826685522889321}
Training time: 1.3094921112060547
{'index': 44, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 10, 'n_estimators': 1000, 'learning_rate': 0.1}, 'rmse': 0.4209767228512498}
Training time: 1.8974757194519043
{'index': 45, 'model_type': 'XGBRegressor', 'hyperparams': {'max_depth': 32, 'n_estimators': 2000, 'learning_rate': 0.1}, 'rmse': 0.3450224401105828}

In [16]:
from sklearn.gaussian_process import GaussianProcessRegressor
from sklearn.gaussian_process.kernels import Matern, ConstantKernel as C, RBF, RationalQuadratic

param_grid = [
    # Matern kernel models
    {
        'kernel': Matern(),  
    },
    {
        'kernel': Matern(),  
    },
    # Quadratic (RBF) kernel models  
    {
        'kernel': RBF(),  
    },
    {
        'kernel': RBF(),
    }
]

for idx, params in enumerate(param_grid):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    start_time = time.time()
    model = GaussianProcessRegressor(kernel=params['kernel'])
    model.fit(X_boot_scaled, y_boot)
    X_val_scaled = scaler.transform(X_val)
    y_val_pred = model.predict(X_val_scaled)
    rmse = root_mean_squared_error(y_val, y_val_pred)
    training_time = time.time() - start_time
    print(f'Training time: {training_time}')
    model_metadata = {
        'index': config_id,
        'model_type': type(model).__name__,
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    
    print(model_metadata)
    models_list.append(model_metadata)

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/sklearn/gaussian_process/_gpr.py:663: ConvergenceWarning: lbfgs failed to converge after 6 iteration(s) (status=2):
ABNORMAL:

You might also want to scale the data as shown in:
    https://scikit-learn.org/stable/modules/preprocessing.html
  _check_optimize_result("lbfgs", opt_res)

Training time: 1.8506176471710205
{'index': 46, 'model_type': 'GaussianProcessRegressor', 'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)}, 'rmse': 0.20052852390943635}
Training time: 0.5480823516845703
{'index': 47, 'model_type': 'GaussianProcessRegressor', 'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)}, 'rmse': 0.21974053165354152}
Training time: 1.2855401039123535
{'index': 48, 'model_type': 'GaussianProcessRegressor', 'hyperparams': {'kernel': RBF(length_scale=1)}, 'rmse': 0.24904687682427573}
Training time: 0.6075630187988281
{'index': 49, 'model_type': 'GaussianProcessRegressor', 'hyperparams': {'kernel': RBF(length_scale=1)}, 'rmse': 0.2371973841890745}

In [17]:
import torch.nn as nn

In [18]:
hyperparams_list = [
    {'n_layers': 2, 'layer_size': 5, 'lr': 0.01, 'l2_reg': 0.01},
    {'n_layers': 2, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1},
    {'n_layers': 3, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1},
    {'n_layers': 3, 'layer_size': 10, 'lr': 0.0005, 'l2_reg': 0.1}
]
for idx, params in enumerate(hyperparams_list):
    
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)

    params.update({
    'input_dim': X_boot.shape[1],
    'output_dim': 1
})
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)

    X_boot_tensor = torch.FloatTensor(X_boot_scaled)
    y_boot_tensor = torch.FloatTensor(y_boot.values)
    train_dataset = TensorDataset(X_boot_tensor, y_boot_tensor)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    X_val_scaled = scaler.transform(X_val)
    X_val_tensor = torch.FloatTensor(X_val_scaled)
    y_val_tensor = torch.FloatTensor(y_val.values)
    val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
    val_loader = DataLoader(val_dataset, batch_size=32)

    # Create MLP
    model, optimizer = create_mlp_pytorch(
        params['input_dim'],
        params['output_dim'], 
        n_layers=params['n_layers'],
        layer_size=params['layer_size'],
        lr=params['lr'],
        l2_reg=params['l2_reg'])
    
    # Training code would go here
    # model.train() ... etc.
    # Basic EarlyStopping for 1000 epochs
    early_stopping = EarlyStopping(patience=20, min_delta=0.001, verbose=True)
    criterion = nn.MSELoss()
  
    train_losses = []
    val_losses = []
    
    for epoch in range(1000):
        # Training phase
        model.train()
        train_loss = 0.0
        for batch_idx, (data, target) in enumerate(train_loader):
            
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        avg_train_loss = train_loss / len(train_loader)
        train_losses.append(avg_train_loss)
        
        # Validation phase
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for data, target in val_loader:
                output = model(data)
                val_loss += criterion(output, target).item()
        
        avg_val_loss = val_loss / len(val_loader)
        val_losses.append(avg_val_loss)
        
        print(f'Epoch {epoch+1}/{1000}, '
                f'Train Loss: {avg_train_loss:.4f}, '
                f'Val Loss: {avg_val_loss:.4f}')
        
        # Early stopping check
        if early_stopping(avg_val_loss, model):
            print("Early stopping triggered. Restoring best model...")
            # Restore the best model
            model.load_state_dict(early_stopping.best_model_state)
            break
    
    model.eval()

    all_predictions = []
    all_targets = []

    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(val_loader):
            predictions = model(data)
            
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(target.numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions, axis=0)
    all_targets = np.concatenate(all_targets, axis=0)

    # Calculate RMSE
    rmse = root_mean_squared_error(all_targets, all_predictions)
    
    # Store metadata
    model_metadata = {
        'index': config_id,
        'model_type': 'MLP_PyTorch',
        'hyperparams': params,
        'rmse': rmse
    }
    config_id += 1
    print(model_metadata)
    models_list.append(model_metadata)

Epoch 1/1000, Train Loss: 1.0674, Val Loss: 1.0285
Validation loss decreased (inf -> 1.028459). Saving model...
Epoch 2/1000, Train Loss: 0.9327, Val Loss: 1.0045
Validation loss decreased (1.028459 -> 1.004511). Saving model...
Epoch 3/1000, Train Loss: 0.9481, Val Loss: 1.0012
Validation loss decreased (1.004511 -> 1.001207). Saving model...
Epoch 4/1000, Train Loss: 0.9251, Val Loss: 1.0202
EarlyStopping counter: 1 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 5/1000, Train Loss: 0.9195, Val Loss: 1.0216
EarlyStopping counter: 2 out of 20
Epoch 6/1000, Train Loss: 1.0213, Val Loss: 1.0089
EarlyStopping counter: 3 out of 20
Epoch 7/1000, Train Loss: 0.9525, Val Loss: 1.0127
EarlyStopping counter: 4 out of 20
Epoch 8/1000, Train Loss: 0.9594, Val Loss: 1.0142
EarlyStopping counter: 5 out of 20
Epoch 9/1000, Train Loss: 0.9233, Val Loss: 1.0129
EarlyStopping counter: 6 out of 20
Epoch 10/1000, Train Loss: 0.9648, Val Loss: 1.0087
EarlyStopping counter: 7 out of 20
Epoch 11/1000, Train Loss: 0.9134, Val Loss: 1.0379
EarlyStopping counter: 8 out of 20
Epoch 12/1000, Train Loss: 0.9164, Val Loss: 1.0059
EarlyStopping counter: 9 out of 20
Epoch 13/1000, Train Loss: 0.9166, Val Loss: 1.0083
EarlyStopping counter: 10 out of 20
Epoch 14/1000, Train Loss: 0.9181, Val Loss: 1.0126
EarlyStopping counter: 11 out of 20
Epoch 15/1000, Train Loss: 1.0435, Val Loss: 1.0155
EarlyStopping counter: 12 out of 20
Epoch 16/1000, Train Loss: 0.9578, Val Loss: 1.0042
EarlyStopping counter: 13 out of 20
Epoch 17/1000, Train Loss: 0.9204, Val Loss: 1.0159
EarlyStopping counter: 14 out of 20
Epoch 18/1000, Train Loss: 0.9105, Val Loss: 1.0104
EarlyStopping counter: 15 out of 20
Epoch 19/1000, Train Loss: 0.9129, Val Loss: 1.0178
EarlyStopping counter: 16 out of 20
Epoch 20/1000, Train Loss: 0.9136, Val Loss: 1.0186
EarlyStopping counter: 17 out of 20
Epoch 21/1000, Train Loss: 0.9149, Val Loss: 1.0183
EarlyStopping counter: 18 out of 20
Epoch 22/1000, Train Loss: 0.9112, Val Loss: 1.0181
EarlyStopping counter: 19 out of 20
Epoch 23/1000, Train Loss: 0.9096, Val Loss: 1.0127
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 50, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 2, 'layer_size': 5, 'lr': 0.01, 'l2_reg': 0.01, 'input_dim': 516, 'output_dim': 1}, 'rmse': 1.0029479265213013}
Epoch 1/1000, Train Loss: 0.7889, Val Loss: 1.0111
Validation loss decreased (inf -> 1.011103). Saving model...
Epoch 2/1000, Train Loss: 0.7936, Val Loss: 1.0164
EarlyStopping counter: 1 out of 20
Epoch 3/1000, Train Loss: 0.7740, Val Loss: 1.0170
EarlyStopping counter: 2 out of 20
Epoch 4/1000, Train Loss: 0.8016, Val Loss: 1.0201
EarlyStopping counter: 3 out of 20
Epoch 5/1000, Train Loss: 0.8043, Val Loss: 1.0275
EarlyStopping counter: 4 out of 20
Epoch 6/1000, Train Loss: 0.7791, Val Loss: 1.0199
EarlyStopping counter: 5 out of 20
Epoch 7/1000, Train Loss: 0.8716, Val Loss: 1.0205
EarlyStopping counter: 6 out of 20
Epoch 8/1000, Train Loss: 0.8192, Val Loss: 1.0284
EarlyStopping counter: 7 out of 20
Epoch 9/1000, Train Loss: 0.7675, Val Loss: 1.0263
EarlyStopping counter: 8 out of 20
Epoch 10/1000, Train Loss: 0.8234, Val Loss: 1.0214
EarlyStopping counter: 9 out of 20
Epoch 11/1000, Train Loss: 0.7688, Val Loss: 1.0194
EarlyStopping counter: 10 out of 20
Epoch 12/1000, Train Loss: 0.7705, Val Loss: 1.0205
EarlyStopping counter: 11 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 13/1000, Train Loss: 0.7681, Val Loss: 1.0196
EarlyStopping counter: 12 out of 20
Epoch 14/1000, Train Loss: 0.8221, Val Loss: 1.0208
EarlyStopping counter: 13 out of 20
Epoch 15/1000, Train Loss: 0.8925, Val Loss: 1.0261
EarlyStopping counter: 14 out of 20
Epoch 16/1000, Train Loss: 0.7735, Val Loss: 1.0207
EarlyStopping counter: 15 out of 20
Epoch 17/1000, Train Loss: 0.7756, Val Loss: 1.0205
EarlyStopping counter: 16 out of 20
Epoch 18/1000, Train Loss: 0.8906, Val Loss: 1.0212
EarlyStopping counter: 17 out of 20
Epoch 19/1000, Train Loss: 0.8421, Val Loss: 1.0187
EarlyStopping counter: 18 out of 20
Epoch 20/1000, Train Loss: 0.7734, Val Loss: 1.0179
EarlyStopping counter: 19 out of 20
Epoch 21/1000, Train Loss: 0.7911, Val Loss: 1.0202
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 51, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 2, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1, 'input_dim': 516, 'output_dim': 1}, 'rmse': 0.989759624004364}
Epoch 1/1000, Train Loss: 0.9551, Val Loss: 1.0696
Validation loss decreased (inf -> 1.069558). Saving model...
Epoch 2/1000, Train Loss: 0.9972, Val Loss: 1.0542
Validation loss decreased (1.069558 -> 1.054160). Saving model...
Epoch 3/1000, Train Loss: 1.0248, Val Loss: 1.0431
Validation loss decreased (1.054160 -> 1.043061). Saving model...
Epoch 4/1000, Train Loss: 0.9961, Val Loss: 1.0461
EarlyStopping counter: 1 out of 20
Epoch 5/1000, Train Loss: 0.9237, Val Loss: 1.0316
Validation loss decreased (1.043061 -> 1.031632). Saving model...

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 6/1000, Train Loss: 0.9201, Val Loss: 1.0300
Validation loss decreased (1.031632 -> 1.030023). Saving model...
Epoch 7/1000, Train Loss: 0.9161, Val Loss: 1.0313
EarlyStopping counter: 1 out of 20
Epoch 8/1000, Train Loss: 0.9271, Val Loss: 1.0297
EarlyStopping counter: 2 out of 20
Epoch 9/1000, Train Loss: 0.9756, Val Loss: 1.0295
EarlyStopping counter: 3 out of 20
Epoch 10/1000, Train Loss: 0.9780, Val Loss: 1.0258
Validation loss decreased (1.030023 -> 1.025794). Saving model...
Epoch 11/1000, Train Loss: 1.0348, Val Loss: 1.0245
Validation loss decreased (1.025794 -> 1.024525). Saving model...
Epoch 12/1000, Train Loss: 0.9399, Val Loss: 1.0294
EarlyStopping counter: 1 out of 20
Epoch 13/1000, Train Loss: 0.9183, Val Loss: 1.0263
EarlyStopping counter: 2 out of 20
Epoch 14/1000, Train Loss: 1.0740, Val Loss: 1.0264
EarlyStopping counter: 3 out of 20
Epoch 15/1000, Train Loss: 0.9224, Val Loss: 1.0285
EarlyStopping counter: 4 out of 20
Epoch 16/1000, Train Loss: 0.9152, Val Loss: 1.0264
EarlyStopping counter: 5 out of 20
Epoch 17/1000, Train Loss: 0.9137, Val Loss: 1.0258
EarlyStopping counter: 6 out of 20
Epoch 18/1000, Train Loss: 0.9157, Val Loss: 1.0246
EarlyStopping counter: 7 out of 20
Epoch 19/1000, Train Loss: 0.9202, Val Loss: 1.0226
Validation loss decreased (1.024525 -> 1.022641). Saving model...
Epoch 20/1000, Train Loss: 1.0353, Val Loss: 1.0201
Validation loss decreased (1.022641 -> 1.020141). Saving model...
Epoch 21/1000, Train Loss: 0.9101, Val Loss: 1.0179
Validation loss decreased (1.020141 -> 1.017869). Saving model...
Epoch 22/1000, Train Loss: 0.9824, Val Loss: 1.0173
EarlyStopping counter: 1 out of 20
Epoch 23/1000, Train Loss: 1.0198, Val Loss: 1.0184
EarlyStopping counter: 2 out of 20
Epoch 24/1000, Train Loss: 0.9200, Val Loss: 1.0206
EarlyStopping counter: 3 out of 20
Epoch 25/1000, Train Loss: 0.9139, Val Loss: 1.0208
EarlyStopping counter: 4 out of 20
Epoch 26/1000, Train Loss: 0.9113, Val Loss: 1.0212
EarlyStopping counter: 5 out of 20
Epoch 27/1000, Train Loss: 0.9130, Val Loss: 1.0201
EarlyStopping counter: 6 out of 20
Epoch 28/1000, Train Loss: 0.9129, Val Loss: 1.0191
EarlyStopping counter: 7 out of 20
Epoch 29/1000, Train Loss: 1.0331, Val Loss: 1.0190
EarlyStopping counter: 8 out of 20
Epoch 30/1000, Train Loss: 0.9376, Val Loss: 1.0201
EarlyStopping counter: 9 out of 20
Epoch 31/1000, Train Loss: 0.9137, Val Loss: 1.0190
EarlyStopping counter: 10 out of 20
Epoch 32/1000, Train Loss: 0.9194, Val Loss: 1.0183
EarlyStopping counter: 11 out of 20
Epoch 33/1000, Train Loss: 1.0020, Val Loss: 1.0184
EarlyStopping counter: 12 out of 20
Epoch 34/1000, Train Loss: 0.9161, Val Loss: 1.0194
EarlyStopping counter: 13 out of 20
Epoch 35/1000, Train Loss: 0.9127, Val Loss: 1.0189
EarlyStopping counter: 14 out of 20
Epoch 36/1000, Train Loss: 0.9416, Val Loss: 1.0177
EarlyStopping counter: 15 out of 20
Epoch 37/1000, Train Loss: 0.9169, Val Loss: 1.0164
Validation loss decreased (1.017869 -> 1.016407). Saving model...
Epoch 38/1000, Train Loss: 0.9142, Val Loss: 1.0162
EarlyStopping counter: 1 out of 20
Epoch 39/1000, Train Loss: 0.9120, Val Loss: 1.0158
EarlyStopping counter: 2 out of 20
Epoch 40/1000, Train Loss: 0.9149, Val Loss: 1.0156
EarlyStopping counter: 3 out of 20
Epoch 41/1000, Train Loss: 1.0682, Val Loss: 1.0149
Validation loss decreased (1.016407 -> 1.014892). Saving model...
Epoch 42/1000, Train Loss: 0.9119, Val Loss: 1.0167
EarlyStopping counter: 1 out of 20
Epoch 43/1000, Train Loss: 0.9402, Val Loss: 1.0168
EarlyStopping counter: 2 out of 20
Epoch 44/1000, Train Loss: 0.9632, Val Loss: 1.0152
EarlyStopping counter: 3 out of 20
Epoch 45/1000, Train Loss: 0.9121, Val Loss: 1.0142
EarlyStopping counter: 4 out of 20
Epoch 46/1000, Train Loss: 0.9461, Val Loss: 1.0136
Validation loss decreased (1.014892 -> 1.013589). Saving model...
Epoch 47/1000, Train Loss: 0.9218, Val Loss: 1.0133
EarlyStopping counter: 1 out of 20
Epoch 48/1000, Train Loss: 0.9429, Val Loss: 1.0136
EarlyStopping counter: 2 out of 20
Epoch 49/1000, Train Loss: 0.9648, Val Loss: 1.0142
EarlyStopping counter: 3 out of 20
Epoch 50/1000, Train Loss: 0.9167, Val Loss: 1.0131
EarlyStopping counter: 4 out of 20
Epoch 51/1000, Train Loss: 0.9153, Val Loss: 1.0137
EarlyStopping counter: 5 out of 20
Epoch 52/1000, Train Loss: 0.9517, Val Loss: 1.0140
EarlyStopping counter: 6 out of 20
Epoch 53/1000, Train Loss: 0.9589, Val Loss: 1.0127
EarlyStopping counter: 7 out of 20
Epoch 54/1000, Train Loss: 0.9477, Val Loss: 1.0119
Validation loss decreased (1.013589 -> 1.011903). Saving model...
Epoch 55/1000, Train Loss: 1.0015, Val Loss: 1.0128
EarlyStopping counter: 1 out of 20
Epoch 56/1000, Train Loss: 0.9304, Val Loss: 1.0148
EarlyStopping counter: 2 out of 20
Epoch 57/1000, Train Loss: 0.9097, Val Loss: 1.0151
EarlyStopping counter: 3 out of 20
Epoch 58/1000, Train Loss: 0.9319, Val Loss: 1.0149
EarlyStopping counter: 4 out of 20
Epoch 59/1000, Train Loss: 0.9270, Val Loss: 1.0140
EarlyStopping counter: 5 out of 20
Epoch 60/1000, Train Loss: 0.9396, Val Loss: 1.0133
EarlyStopping counter: 6 out of 20
Epoch 61/1000, Train Loss: 0.9413, Val Loss: 1.0127
EarlyStopping counter: 7 out of 20
Epoch 62/1000, Train Loss: 0.9382, Val Loss: 1.0132
EarlyStopping counter: 8 out of 20
Epoch 63/1000, Train Loss: 0.9473, Val Loss: 1.0127
EarlyStopping counter: 9 out of 20
Epoch 64/1000, Train Loss: 0.9254, Val Loss: 1.0137
EarlyStopping counter: 10 out of 20
Epoch 65/1000, Train Loss: 0.9252, Val Loss: 1.0141
EarlyStopping counter: 11 out of 20
Epoch 66/1000, Train Loss: 1.0393, Val Loss: 1.0149
EarlyStopping counter: 12 out of 20
Epoch 67/1000, Train Loss: 0.9127, Val Loss: 1.0159
EarlyStopping counter: 13 out of 20
Epoch 68/1000, Train Loss: 0.9604, Val Loss: 1.0160
EarlyStopping counter: 14 out of 20
Epoch 69/1000, Train Loss: 0.9598, Val Loss: 1.0146
EarlyStopping counter: 15 out of 20
Epoch 70/1000, Train Loss: 0.9099, Val Loss: 1.0153
EarlyStopping counter: 16 out of 20
Epoch 71/1000, Train Loss: 0.9405, Val Loss: 1.0154
EarlyStopping counter: 17 out of 20
Epoch 72/1000, Train Loss: 0.9323, Val Loss: 1.0156
EarlyStopping counter: 18 out of 20
Epoch 73/1000, Train Loss: 0.9171, Val Loss: 1.0150
EarlyStopping counter: 19 out of 20
Epoch 74/1000, Train Loss: 0.9118, Val Loss: 1.0150
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 52, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 3, 'layer_size': 10, 'lr': 0.001, 'l2_reg': 0.1, 'input_dim': 516, 'output_dim': 1}, 'rmse': 1.0059338808059692}
Epoch 1/1000, Train Loss: 1.0598, Val Loss: 1.0886
Validation loss decreased (inf -> 1.088647). Saving model...
Epoch 2/1000, Train Loss: 1.0091, Val Loss: 1.0837
Validation loss decreased (1.088647 -> 1.083743). Saving model...
Epoch 3/1000, Train Loss: 1.0024, Val Loss: 1.0760
Validation loss decreased (1.083743 -> 1.075972). Saving model...
Epoch 4/1000, Train Loss: 1.0149, Val Loss: 1.0701
Validation loss decreased (1.075972 -> 1.070068). Saving model...
Epoch 5/1000, Train Loss: 0.9929, Val Loss: 1.0656
Validation loss decreased (1.070068 -> 1.065639). Saving model...

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 6/1000, Train Loss: 0.9866, Val Loss: 1.0606
Validation loss decreased (1.065639 -> 1.060607). Saving model...
Epoch 7/1000, Train Loss: 1.0027, Val Loss: 1.0562
Validation loss decreased (1.060607 -> 1.056243). Saving model...
Epoch 8/1000, Train Loss: 1.0048, Val Loss: 1.0538
Validation loss decreased (1.056243 -> 1.053829). Saving model...
Epoch 9/1000, Train Loss: 0.9863, Val Loss: 1.0488
Validation loss decreased (1.053829 -> 1.048750). Saving model...
Epoch 10/1000, Train Loss: 1.0440, Val Loss: 1.0451
Validation loss decreased (1.048750 -> 1.045103). Saving model...
Epoch 11/1000, Train Loss: 0.9803, Val Loss: 1.0416
Validation loss decreased (1.045103 -> 1.041569). Saving model...
Epoch 12/1000, Train Loss: 0.9823, Val Loss: 1.0396
Validation loss decreased (1.041569 -> 1.039577). Saving model...
Epoch 13/1000, Train Loss: 1.0252, Val Loss: 1.0379
Validation loss decreased (1.039577 -> 1.037902). Saving model...
Epoch 14/1000, Train Loss: 0.9760, Val Loss: 1.0371
EarlyStopping counter: 1 out of 20
Epoch 15/1000, Train Loss: 1.1121, Val Loss: 1.0356
Validation loss decreased (1.037902 -> 1.035587). Saving model...
Epoch 16/1000, Train Loss: 1.0072, Val Loss: 1.0358
EarlyStopping counter: 1 out of 20
Epoch 17/1000, Train Loss: 1.0796, Val Loss: 1.0348
EarlyStopping counter: 2 out of 20
Epoch 18/1000, Train Loss: 1.1075, Val Loss: 1.0316
Validation loss decreased (1.035587 -> 1.031593). Saving model...
Epoch 19/1000, Train Loss: 0.9904, Val Loss: 1.0285
Validation loss decreased (1.031593 -> 1.028481). Saving model...
Epoch 20/1000, Train Loss: 0.9717, Val Loss: 1.0265
Validation loss decreased (1.028481 -> 1.026456). Saving model...
Epoch 21/1000, Train Loss: 0.9983, Val Loss: 1.0259
EarlyStopping counter: 1 out of 20
Epoch 22/1000, Train Loss: 0.9716, Val Loss: 1.0252
Validation loss decreased (1.026456 -> 1.025241). Saving model...
Epoch 23/1000, Train Loss: 1.0005, Val Loss: 1.0245
EarlyStopping counter: 1 out of 20
Epoch 24/1000, Train Loss: 0.9876, Val Loss: 1.0240
Validation loss decreased (1.025241 -> 1.023965). Saving model...
Epoch 25/1000, Train Loss: 0.9707, Val Loss: 1.0240
EarlyStopping counter: 1 out of 20
Epoch 26/1000, Train Loss: 0.9918, Val Loss: 1.0236
EarlyStopping counter: 2 out of 20
Epoch 27/1000, Train Loss: 1.0358, Val Loss: 1.0230
Validation loss decreased (1.023965 -> 1.022963). Saving model...
Epoch 28/1000, Train Loss: 0.9730, Val Loss: 1.0231
EarlyStopping counter: 1 out of 20
Epoch 29/1000, Train Loss: 1.0016, Val Loss: 1.0223
EarlyStopping counter: 2 out of 20
Epoch 30/1000, Train Loss: 0.9918, Val Loss: 1.0210
Validation loss decreased (1.022963 -> 1.021028). Saving model...
Epoch 31/1000, Train Loss: 0.9769, Val Loss: 1.0208
EarlyStopping counter: 1 out of 20
Epoch 32/1000, Train Loss: 0.9735, Val Loss: 1.0204
EarlyStopping counter: 2 out of 20
Epoch 33/1000, Train Loss: 1.0061, Val Loss: 1.0199
Validation loss decreased (1.021028 -> 1.019858). Saving model...
Epoch 34/1000, Train Loss: 0.9822, Val Loss: 1.0183
Validation loss decreased (1.019858 -> 1.018314). Saving model...
Epoch 35/1000, Train Loss: 0.9725, Val Loss: 1.0173
Validation loss decreased (1.018314 -> 1.017300). Saving model...
Epoch 36/1000, Train Loss: 0.9701, Val Loss: 1.0169
EarlyStopping counter: 1 out of 20
Epoch 37/1000, Train Loss: 0.9950, Val Loss: 1.0165
EarlyStopping counter: 2 out of 20
Epoch 38/1000, Train Loss: 0.9711, Val Loss: 1.0158
Validation loss decreased (1.017300 -> 1.015760). Saving model...
Epoch 39/1000, Train Loss: 0.9731, Val Loss: 1.0152
EarlyStopping counter: 1 out of 20
Epoch 40/1000, Train Loss: 0.9741, Val Loss: 1.0153
EarlyStopping counter: 2 out of 20
Epoch 41/1000, Train Loss: 1.0374, Val Loss: 1.0152
EarlyStopping counter: 3 out of 20
Epoch 42/1000, Train Loss: 0.9722, Val Loss: 1.0153
EarlyStopping counter: 4 out of 20
Epoch 43/1000, Train Loss: 1.0966, Val Loss: 1.0153
EarlyStopping counter: 5 out of 20
Epoch 44/1000, Train Loss: 0.9977, Val Loss: 1.0156
EarlyStopping counter: 6 out of 20
Epoch 45/1000, Train Loss: 0.9736, Val Loss: 1.0150
EarlyStopping counter: 7 out of 20
Epoch 46/1000, Train Loss: 0.9787, Val Loss: 1.0144
Validation loss decreased (1.015760 -> 1.014437). Saving model...
Epoch 47/1000, Train Loss: 1.1164, Val Loss: 1.0145
EarlyStopping counter: 1 out of 20
Epoch 48/1000, Train Loss: 0.9903, Val Loss: 1.0151
EarlyStopping counter: 2 out of 20
Epoch 49/1000, Train Loss: 1.0386, Val Loss: 1.0154
EarlyStopping counter: 3 out of 20
Epoch 50/1000, Train Loss: 0.9868, Val Loss: 1.0156
EarlyStopping counter: 4 out of 20
Epoch 51/1000, Train Loss: 0.9699, Val Loss: 1.0150
EarlyStopping counter: 5 out of 20
Epoch 52/1000, Train Loss: 0.9692, Val Loss: 1.0149
EarlyStopping counter: 6 out of 20
Epoch 53/1000, Train Loss: 0.9850, Val Loss: 1.0144
EarlyStopping counter: 7 out of 20
Epoch 54/1000, Train Loss: 1.1325, Val Loss: 1.0137
EarlyStopping counter: 8 out of 20
Epoch 55/1000, Train Loss: 0.9689, Val Loss: 1.0127
Validation loss decreased (1.014437 -> 1.012664). Saving model...
Epoch 56/1000, Train Loss: 0.9689, Val Loss: 1.0123
EarlyStopping counter: 1 out of 20
Epoch 57/1000, Train Loss: 1.0283, Val Loss: 1.0122
EarlyStopping counter: 2 out of 20
Epoch 58/1000, Train Loss: 0.9777, Val Loss: 1.0114
Validation loss decreased (1.012664 -> 1.011394). Saving model...
Epoch 59/1000, Train Loss: 0.9977, Val Loss: 1.0114
EarlyStopping counter: 1 out of 20
Epoch 60/1000, Train Loss: 1.1200, Val Loss: 1.0119
EarlyStopping counter: 2 out of 20
Epoch 61/1000, Train Loss: 0.9858, Val Loss: 1.0124
EarlyStopping counter: 3 out of 20
Epoch 62/1000, Train Loss: 0.9688, Val Loss: 1.0121
EarlyStopping counter: 4 out of 20
Epoch 63/1000, Train Loss: 0.9689, Val Loss: 1.0120
EarlyStopping counter: 5 out of 20
Epoch 64/1000, Train Loss: 1.0100, Val Loss: 1.0118
EarlyStopping counter: 6 out of 20
Epoch 65/1000, Train Loss: 0.9699, Val Loss: 1.0113
EarlyStopping counter: 7 out of 20
Epoch 66/1000, Train Loss: 1.0405, Val Loss: 1.0111
EarlyStopping counter: 8 out of 20
Epoch 67/1000, Train Loss: 1.0174, Val Loss: 1.0117
EarlyStopping counter: 9 out of 20
Epoch 68/1000, Train Loss: 0.9893, Val Loss: 1.0121
EarlyStopping counter: 10 out of 20
Epoch 69/1000, Train Loss: 0.9871, Val Loss: 1.0122
EarlyStopping counter: 11 out of 20
Epoch 70/1000, Train Loss: 0.9693, Val Loss: 1.0117
EarlyStopping counter: 12 out of 20
Epoch 71/1000, Train Loss: 1.8363, Val Loss: 1.0116
EarlyStopping counter: 13 out of 20
Epoch 72/1000, Train Loss: 0.9879, Val Loss: 1.0101
Validation loss decreased (1.011394 -> 1.010073). Saving model...
Epoch 73/1000, Train Loss: 1.0038, Val Loss: 1.0094
EarlyStopping counter: 1 out of 20
Epoch 74/1000, Train Loss: 1.0209, Val Loss: 1.0090
Validation loss decreased (1.010073 -> 1.008991). Saving model...
Epoch 75/1000, Train Loss: 0.9691, Val Loss: 1.0092
EarlyStopping counter: 1 out of 20
Epoch 76/1000, Train Loss: 1.0090, Val Loss: 1.0093
EarlyStopping counter: 2 out of 20
Epoch 77/1000, Train Loss: 0.9896, Val Loss: 1.0097
EarlyStopping counter: 3 out of 20
Epoch 78/1000, Train Loss: 0.9729, Val Loss: 1.0099
EarlyStopping counter: 4 out of 20
Epoch 79/1000, Train Loss: 0.9688, Val Loss: 1.0100
EarlyStopping counter: 5 out of 20
Epoch 80/1000, Train Loss: 0.9905, Val Loss: 1.0100
EarlyStopping counter: 6 out of 20
Epoch 81/1000, Train Loss: 1.0918, Val Loss: 1.0097
EarlyStopping counter: 7 out of 20
Epoch 82/1000, Train Loss: 0.9734, Val Loss: 1.0091
EarlyStopping counter: 8 out of 20
Epoch 83/1000, Train Loss: 0.9693, Val Loss: 1.0089
EarlyStopping counter: 9 out of 20
Epoch 84/1000, Train Loss: 0.9689, Val Loss: 1.0087
EarlyStopping counter: 10 out of 20
Epoch 85/1000, Train Loss: 0.9717, Val Loss: 1.0087
EarlyStopping counter: 11 out of 20
Epoch 86/1000, Train Loss: 0.9710, Val Loss: 1.0090
EarlyStopping counter: 12 out of 20
Epoch 87/1000, Train Loss: 1.0416, Val Loss: 1.0091
EarlyStopping counter: 13 out of 20
Epoch 88/1000, Train Loss: 1.0184, Val Loss: 1.0095
EarlyStopping counter: 14 out of 20
Epoch 89/1000, Train Loss: 0.9699, Val Loss: 1.0098
EarlyStopping counter: 15 out of 20
Epoch 90/1000, Train Loss: 0.9871, Val Loss: 1.0098
EarlyStopping counter: 16 out of 20
Epoch 91/1000, Train Loss: 0.9936, Val Loss: 1.0096
EarlyStopping counter: 17 out of 20
Epoch 92/1000, Train Loss: 0.9702, Val Loss: 1.0099
EarlyStopping counter: 18 out of 20
Epoch 93/1000, Train Loss: 0.9965, Val Loss: 1.0099
EarlyStopping counter: 19 out of 20
Epoch 94/1000, Train Loss: 1.1528, Val Loss: 1.0096
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 53, 'model_type': 'MLP_PyTorch', 'hyperparams': {'n_layers': 3, 'layer_size': 10, 'lr': 0.0005, 'l2_reg': 0.1, 'input_dim': 516, 'output_dim': 1}, 'rmse': 1.0044853687286377}

In [19]:
def create_mlp_resnet(input_dim, output_dim, block_dim, hidden_dim, num_blocks, lr, l2_reg):
    model = ResNet(
        input_dim = input_dim,
        output_dim = output_dim,
        num_blocks = num_blocks,
        hidden_dim = hidden_dim,
        block_dim = block_dim
    )
    optimizer = optim.Adam(model.parameters(), lr, weight_decay=l2_reg)

    return model, optimizer

In [20]:
specified_configs = [
    # D block D hidden N blocks Learning rate L2 regularisation
    {'block_dim': 16, 'hidden_dim': 8, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.01},
    {'block_dim': 32, 'hidden_dim': 16, 'num_blocks': 2, 'lr': 0.01, 'l2_reg': 0.1},
    {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.01},
    {'block_dim': 64, 'hidden_dim': 32, 'num_blocks': 3, 'lr': 0.001, 'l2_reg': 0.1},
]

for idx, params in enumerate(specified_configs):
    seed = base_seed + config_id
    X_boot, y_boot = resample(
    X_train, y_train,
    replace=True,
    n_samples=len(X_train),
    random_state=seed)
    params.update({
    'input_dim': X_boot.shape[1],
    'output_dim': 1
})
    scaler = StandardScaler()
    X_boot_scaled = scaler.fit_transform(X_boot)
    X_boot_tensor = torch.FloatTensor(X_boot_scaled)
    y_boot_tensor = torch.FloatTensor(y_boot.values)
    train_dataset = TensorDataset(X_boot_tensor, y_boot_tensor)
    train_loader = DataLoader(train_dataset, batch_size=32, shuffle=True)

    X_val_scaled = scaler.transform(X_val)
    X_val_tensor = torch.FloatTensor(X_val_scaled)
    y_val_tensor = torch.FloatTensor(y_val.values)
    val_dataset = TensorDataset(X_val_tensor, y_val_tensor)
    val_loader = DataLoader(val_dataset, batch_size=32)

    model, optimizer = create_mlp_resnet(
        input_dim = params['input_dim'], 
        output_dim = params['output_dim'],
        num_blocks=params['num_blocks'],
        hidden_dim=params['hidden_dim'],
        block_dim=params['block_dim'],
        lr=params['lr'],
        l2_reg=params['l2_reg'])

    early_stopping = EarlyStopping(patience=20, min_delta=0.001, verbose=True)
    criterion = nn.MSELoss()

    early_stopping = EarlyStopping(patience=20, min_delta=0.001, verbose=True)
    criterion = nn.MSELoss()
  
    train_losses = []
    val_losses = []
    
    for epoch in range(1000):
        # Training phase
        model.train()
        train_loss = 0.0
        for batch_idx, (data, target) in enumerate(train_loader):
            
            optimizer.zero_grad()
            output = model(data)
            loss = criterion(output, target)
            loss.backward()
            optimizer.step()
            
            train_loss += loss.item()
        
        avg_train_loss = train_loss / len(train_loader)
        train_losses.append(avg_train_loss)
        
        # Validation phase
        model.eval()
        val_loss = 0.0
        with torch.no_grad():
            for data, target in val_loader:
                output = model(data)
                val_loss += criterion(output, target).item()
        
        avg_val_loss = val_loss / len(val_loader)
        val_losses.append(avg_val_loss)
        
        print(f'Epoch {epoch+1}/{1000}, '
                f'Train Loss: {avg_train_loss:.4f}, '
                f'Val Loss: {avg_val_loss:.4f}')
        
        # Early stopping check
        if early_stopping(avg_val_loss, model):
            print("Early stopping triggered. Restoring best model...")
            # Restore the best model
            model.load_state_dict(early_stopping.best_model_state)
            break
    
    model.eval()

    all_predictions = []
    all_targets = []

    with torch.no_grad():
        for batch_idx, (data, target) in enumerate(val_loader):
            predictions = model(data)
            
            all_predictions.append(predictions.cpu().numpy())
            all_targets.append(target.numpy())

    # Concatenate all batches
    all_predictions = np.concatenate(all_predictions, axis=0)
    all_targets = np.concatenate(all_targets, axis=0)

    # Calculate RMSE
    rmse = root_mean_squared_error(all_targets, all_predictions)
    
    # Store metadata
    model_metadata = {
        'index': config_id,
        'model_type': 'ResNet',
        'hyperparams': None,
        'rmse': rmse
    }
    config_id += 1
    print(model_metadata)
    models_list.append(model_metadata)

Epoch 1/1000, Train Loss: 1.0931, Val Loss: 1.2276
Validation loss decreased (inf -> 1.227566). Saving model...
Epoch 2/1000, Train Loss: 1.0475, Val Loss: 1.0180
Validation loss decreased (1.227566 -> 1.018016). Saving model...
Epoch 3/1000, Train Loss: 0.9632, Val Loss: 1.0230
EarlyStopping counter: 1 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 4/1000, Train Loss: 0.9669, Val Loss: 1.1002
EarlyStopping counter: 2 out of 20
Epoch 5/1000, Train Loss: 1.1287, Val Loss: 1.0309
EarlyStopping counter: 3 out of 20
Epoch 6/1000, Train Loss: 1.0124, Val Loss: 1.0620
EarlyStopping counter: 4 out of 20
Epoch 7/1000, Train Loss: 0.9553, Val Loss: 1.0538
EarlyStopping counter: 5 out of 20
Epoch 8/1000, Train Loss: 0.9513, Val Loss: 1.0848
EarlyStopping counter: 6 out of 20
Epoch 9/1000, Train Loss: 0.9841, Val Loss: 1.0194
EarlyStopping counter: 7 out of 20
Epoch 10/1000, Train Loss: 0.9493, Val Loss: 1.0011
Validation loss decreased (1.018016 -> 1.001072). Saving model...
Epoch 11/1000, Train Loss: 0.9846, Val Loss: 1.0223
EarlyStopping counter: 1 out of 20
Epoch 12/1000, Train Loss: 0.9537, Val Loss: 1.0058
EarlyStopping counter: 2 out of 20
Epoch 13/1000, Train Loss: 0.9558, Val Loss: 1.0480
EarlyStopping counter: 3 out of 20
Epoch 14/1000, Train Loss: 0.9506, Val Loss: 1.0261
EarlyStopping counter: 4 out of 20
Epoch 15/1000, Train Loss: 1.0199, Val Loss: 1.0288
EarlyStopping counter: 5 out of 20
Epoch 16/1000, Train Loss: 0.9514, Val Loss: 1.0061
EarlyStopping counter: 6 out of 20
Epoch 17/1000, Train Loss: 0.9795, Val Loss: 1.0196
EarlyStopping counter: 7 out of 20
Epoch 18/1000, Train Loss: 0.9497, Val Loss: 1.0542
EarlyStopping counter: 8 out of 20
Epoch 19/1000, Train Loss: 0.9946, Val Loss: 1.0073
EarlyStopping counter: 9 out of 20
Epoch 20/1000, Train Loss: 0.9518, Val Loss: 1.0224
EarlyStopping counter: 10 out of 20
Epoch 21/1000, Train Loss: 0.9456, Val Loss: 1.0203
EarlyStopping counter: 11 out of 20
Epoch 22/1000, Train Loss: 0.9360, Val Loss: 1.0142
EarlyStopping counter: 12 out of 20
Epoch 23/1000, Train Loss: 0.9310, Val Loss: 1.0183
EarlyStopping counter: 13 out of 20
Epoch 24/1000, Train Loss: 1.0415, Val Loss: 1.0098
EarlyStopping counter: 14 out of 20
Epoch 25/1000, Train Loss: 1.0650, Val Loss: 1.0684
EarlyStopping counter: 15 out of 20
Epoch 26/1000, Train Loss: 1.0925, Val Loss: 1.4340
EarlyStopping counter: 16 out of 20
Epoch 27/1000, Train Loss: 0.9780, Val Loss: 1.1093
EarlyStopping counter: 17 out of 20
Epoch 28/1000, Train Loss: 0.9440, Val Loss: 1.0036
EarlyStopping counter: 18 out of 20
Epoch 29/1000, Train Loss: 0.9945, Val Loss: 1.0111
EarlyStopping counter: 19 out of 20
Epoch 30/1000, Train Loss: 1.0659, Val Loss: 1.0077
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 54, 'model_type': 'ResNet', 'hyperparams': None, 'rmse': 0.9616740345954895}
Epoch 1/1000, Train Loss: 1.3469, Val Loss: 1.1908
Validation loss decreased (inf -> 1.190843). Saving model...
Epoch 2/1000, Train Loss: 0.9963, Val Loss: 1.0055
Validation loss decreased (1.190843 -> 1.005454). Saving model...
Epoch 3/1000, Train Loss: 0.9266, Val Loss: 1.0102
EarlyStopping counter: 1 out of 20
Epoch 4/1000, Train Loss: 0.9546, Val Loss: 1.0281
EarlyStopping counter: 2 out of 20
Epoch 5/1000, Train Loss: 1.0795, Val Loss: 1.0289
EarlyStopping counter: 3 out of 20
Epoch 6/1000, Train Loss: 0.9405, Val Loss: 1.0571
EarlyStopping counter: 4 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 7/1000, Train Loss: 0.9290, Val Loss: 1.0083
EarlyStopping counter: 5 out of 20
Epoch 8/1000, Train Loss: 0.9100, Val Loss: 1.0346
EarlyStopping counter: 6 out of 20
Epoch 9/1000, Train Loss: 0.9740, Val Loss: 1.0143
EarlyStopping counter: 7 out of 20
Epoch 10/1000, Train Loss: 0.9260, Val Loss: 1.0179
EarlyStopping counter: 8 out of 20
Epoch 11/1000, Train Loss: 1.0282, Val Loss: 1.0142
EarlyStopping counter: 9 out of 20
Epoch 12/1000, Train Loss: 0.9093, Val Loss: 1.0251
EarlyStopping counter: 10 out of 20
Epoch 13/1000, Train Loss: 0.9196, Val Loss: 1.0074
EarlyStopping counter: 11 out of 20
Epoch 14/1000, Train Loss: 0.9806, Val Loss: 1.0508
EarlyStopping counter: 12 out of 20
Epoch 15/1000, Train Loss: 0.9749, Val Loss: 1.0279
EarlyStopping counter: 13 out of 20
Epoch 16/1000, Train Loss: 0.9372, Val Loss: 1.0072
EarlyStopping counter: 14 out of 20
Epoch 17/1000, Train Loss: 0.9424, Val Loss: 1.0121
EarlyStopping counter: 15 out of 20
Epoch 18/1000, Train Loss: 0.9066, Val Loss: 1.0098
EarlyStopping counter: 16 out of 20
Epoch 19/1000, Train Loss: 1.0437, Val Loss: 1.0079
EarlyStopping counter: 17 out of 20
Epoch 20/1000, Train Loss: 0.9409, Val Loss: 1.0024
Validation loss decreased (1.005454 -> 1.002383). Saving model...
Epoch 21/1000, Train Loss: 0.9738, Val Loss: 1.0015
EarlyStopping counter: 1 out of 20
Epoch 22/1000, Train Loss: 0.9402, Val Loss: 0.9989
Validation loss decreased (1.002383 -> 0.998901). Saving model...
Epoch 23/1000, Train Loss: 1.3089, Val Loss: 0.9998
EarlyStopping counter: 1 out of 20
Epoch 24/1000, Train Loss: 1.0364, Val Loss: 1.0463
EarlyStopping counter: 2 out of 20
Epoch 25/1000, Train Loss: 0.9895, Val Loss: 1.0044
EarlyStopping counter: 3 out of 20
Epoch 26/1000, Train Loss: 0.9300, Val Loss: 1.0030
EarlyStopping counter: 4 out of 20
Epoch 27/1000, Train Loss: 0.9078, Val Loss: 0.9990
EarlyStopping counter: 5 out of 20
Epoch 28/1000, Train Loss: 0.9700, Val Loss: 1.0056
EarlyStopping counter: 6 out of 20
Epoch 29/1000, Train Loss: 0.9200, Val Loss: 1.0179
EarlyStopping counter: 7 out of 20
Epoch 30/1000, Train Loss: 0.9592, Val Loss: 1.0156
EarlyStopping counter: 8 out of 20
Epoch 31/1000, Train Loss: 0.9442, Val Loss: 1.0145
EarlyStopping counter: 9 out of 20
Epoch 32/1000, Train Loss: 0.9500, Val Loss: 1.0038
EarlyStopping counter: 10 out of 20
Epoch 33/1000, Train Loss: 0.9178, Val Loss: 1.0023
EarlyStopping counter: 11 out of 20
Epoch 34/1000, Train Loss: 0.9151, Val Loss: 1.0006
EarlyStopping counter: 12 out of 20
Epoch 35/1000, Train Loss: 0.9325, Val Loss: 1.0074
EarlyStopping counter: 13 out of 20
Epoch 36/1000, Train Loss: 1.0235, Val Loss: 1.0054
EarlyStopping counter: 14 out of 20
Epoch 37/1000, Train Loss: 0.9107, Val Loss: 1.0117
EarlyStopping counter: 15 out of 20
Epoch 38/1000, Train Loss: 0.9765, Val Loss: 1.0065
EarlyStopping counter: 16 out of 20
Epoch 39/1000, Train Loss: 0.9087, Val Loss: 1.0131
EarlyStopping counter: 17 out of 20
Epoch 40/1000, Train Loss: 1.0086, Val Loss: 1.0112
EarlyStopping counter: 18 out of 20
Epoch 41/1000, Train Loss: 0.9869, Val Loss: 1.0036
EarlyStopping counter: 19 out of 20
Epoch 42/1000, Train Loss: 0.9064, Val Loss: 1.0114
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 55, 'model_type': 'ResNet', 'hyperparams': None, 'rmse': 0.9884374737739563}
Epoch 1/1000, Train Loss: 0.8709, Val Loss: 1.0235
Validation loss decreased (inf -> 1.023460). Saving model...
Epoch 2/1000, Train Loss: 0.8550, Val Loss: 1.0099
Validation loss decreased (1.023460 -> 1.009888). Saving model...
Epoch 3/1000, Train Loss: 0.8734, Val Loss: 1.0339
EarlyStopping counter: 1 out of 20
Epoch 4/1000, Train Loss: 0.8738, Val Loss: 1.0284
EarlyStopping counter: 2 out of 20
Epoch 5/1000, Train Loss: 0.8511, Val Loss: 1.0106
EarlyStopping counter: 3 out of 20
Epoch 6/1000, Train Loss: 0.8456, Val Loss: 1.0256
EarlyStopping counter: 4 out of 20
Epoch 7/1000, Train Loss: 0.8436, Val Loss: 1.0180
EarlyStopping counter: 5 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 8/1000, Train Loss: 0.8417, Val Loss: 1.0118
EarlyStopping counter: 6 out of 20
Epoch 9/1000, Train Loss: 0.8368, Val Loss: 1.0103
EarlyStopping counter: 7 out of 20
Epoch 10/1000, Train Loss: 0.8653, Val Loss: 1.0130
EarlyStopping counter: 8 out of 20
Epoch 11/1000, Train Loss: 0.9755, Val Loss: 1.0059
Validation loss decreased (1.009888 -> 1.005888). Saving model...
Epoch 12/1000, Train Loss: 0.9397, Val Loss: 1.0395
EarlyStopping counter: 1 out of 20
Epoch 13/1000, Train Loss: 0.8619, Val Loss: 1.0213
EarlyStopping counter: 2 out of 20
Epoch 14/1000, Train Loss: 0.8475, Val Loss: 1.0299
EarlyStopping counter: 3 out of 20
Epoch 15/1000, Train Loss: 0.8471, Val Loss: 1.0108
EarlyStopping counter: 4 out of 20
Epoch 16/1000, Train Loss: 0.8641, Val Loss: 1.0203
EarlyStopping counter: 5 out of 20
Epoch 17/1000, Train Loss: 0.9979, Val Loss: 1.0186
EarlyStopping counter: 6 out of 20
Epoch 18/1000, Train Loss: 0.9010, Val Loss: 1.0372
EarlyStopping counter: 7 out of 20
Epoch 19/1000, Train Loss: 0.8591, Val Loss: 1.0141
EarlyStopping counter: 8 out of 20
Epoch 20/1000, Train Loss: 0.8374, Val Loss: 1.0103
EarlyStopping counter: 9 out of 20
Epoch 21/1000, Train Loss: 0.8611, Val Loss: 1.0171
EarlyStopping counter: 10 out of 20
Epoch 22/1000, Train Loss: 0.8648, Val Loss: 1.0122
EarlyStopping counter: 11 out of 20
Epoch 23/1000, Train Loss: 0.8613, Val Loss: 1.0119
EarlyStopping counter: 12 out of 20
Epoch 24/1000, Train Loss: 0.8842, Val Loss: 1.0225
EarlyStopping counter: 13 out of 20
Epoch 25/1000, Train Loss: 0.8853, Val Loss: 1.0191
EarlyStopping counter: 14 out of 20
Epoch 26/1000, Train Loss: 0.8585, Val Loss: 1.0056
EarlyStopping counter: 15 out of 20
Epoch 27/1000, Train Loss: 0.8431, Val Loss: 1.0097
EarlyStopping counter: 16 out of 20
Epoch 28/1000, Train Loss: 0.8799, Val Loss: 1.0189
EarlyStopping counter: 17 out of 20
Epoch 29/1000, Train Loss: 0.8599, Val Loss: 1.0116
EarlyStopping counter: 18 out of 20
Epoch 30/1000, Train Loss: 0.8491, Val Loss: 1.0094
EarlyStopping counter: 19 out of 20
Epoch 31/1000, Train Loss: 0.9654, Val Loss: 1.0109
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 56, 'model_type': 'ResNet', 'hyperparams': None, 'rmse': 0.9474957585334778}
Epoch 1/1000, Train Loss: 1.0207, Val Loss: 1.0183
Validation loss decreased (inf -> 1.018294). Saving model...
Epoch 2/1000, Train Loss: 1.0088, Val Loss: 1.0087
Validation loss decreased (1.018294 -> 1.008675). Saving model...
Epoch 3/1000, Train Loss: 1.0581, Val Loss: 1.0205
EarlyStopping counter: 1 out of 20

/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([32])) that is different to the input size (torch.Size([32, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)
/home/prati/miniconda3/envs/chemprop_env/lib/python3.11/site-packages/torch/nn/modules/loss.py:608: UserWarning: Using a target size (torch.Size([1])) that is different to the input size (torch.Size([1, 1])). This will likely lead to incorrect results due to broadcasting. Please ensure they have the same size.
  return F.mse_loss(input, target, reduction=self.reduction)

Epoch 4/1000, Train Loss: 1.0347, Val Loss: 1.0670
EarlyStopping counter: 2 out of 20
Epoch 5/1000, Train Loss: 1.3468, Val Loss: 1.0106
EarlyStopping counter: 3 out of 20
Epoch 6/1000, Train Loss: 1.2803, Val Loss: 1.0299
EarlyStopping counter: 4 out of 20
Epoch 7/1000, Train Loss: 1.0379, Val Loss: 1.0209
EarlyStopping counter: 5 out of 20
Epoch 8/1000, Train Loss: 1.2133, Val Loss: 1.0440
EarlyStopping counter: 6 out of 20
Epoch 9/1000, Train Loss: 1.0443, Val Loss: 1.0226
EarlyStopping counter: 7 out of 20
Epoch 10/1000, Train Loss: 1.0306, Val Loss: 1.0303
EarlyStopping counter: 8 out of 20
Epoch 11/1000, Train Loss: 1.1031, Val Loss: 1.0362
EarlyStopping counter: 9 out of 20
Epoch 12/1000, Train Loss: 1.0228, Val Loss: 1.0300
EarlyStopping counter: 10 out of 20
Epoch 13/1000, Train Loss: 0.9992, Val Loss: 1.0243
EarlyStopping counter: 11 out of 20
Epoch 14/1000, Train Loss: 1.0509, Val Loss: 1.0338
EarlyStopping counter: 12 out of 20
Epoch 15/1000, Train Loss: 1.1300, Val Loss: 1.0296
EarlyStopping counter: 13 out of 20
Epoch 16/1000, Train Loss: 1.0011, Val Loss: 1.0316
EarlyStopping counter: 14 out of 20
Epoch 17/1000, Train Loss: 1.1251, Val Loss: 1.0272
EarlyStopping counter: 15 out of 20
Epoch 18/1000, Train Loss: 1.0389, Val Loss: 1.0543
EarlyStopping counter: 16 out of 20
Epoch 19/1000, Train Loss: 1.0091, Val Loss: 1.0297
EarlyStopping counter: 17 out of 20
Epoch 20/1000, Train Loss: 0.9999, Val Loss: 1.0180
EarlyStopping counter: 18 out of 20
Epoch 21/1000, Train Loss: 0.9916, Val Loss: 1.0253
EarlyStopping counter: 19 out of 20
Epoch 22/1000, Train Loss: 0.9974, Val Loss: 1.0165
EarlyStopping counter: 20 out of 20
Early stopping triggered
Early stopping triggered. Restoring best model...
{'index': 57, 'model_type': 'ResNet', 'hyperparams': None, 'rmse': 1.0045675039291382}

In [21]:
models_list

[{'index': 0,
  'model_type': 'KNeighborsRegressor',
  'hyperparams': {},
  'rmse': 0.30109799755193034},
 {'index': 1,
  'model_type': 'KNeighborsRegressor',
  'hyperparams': {},
  'rmse': 0.4657266303774585},
 {'index': 2,
  'model_type': 'KNeighborsRegressor',
  'hyperparams': {},
  'rmse': 0.4090489627021739},
 {'index': 3,
  'model_type': 'KNeighborsRegressor',
  'hyperparams': {},
  'rmse': 0.33176904431885146},
 {'index': 4,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.001},
  'rmse': 0.26280552998679335},
 {'index': 5,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.002},
  'rmse': 0.25729733201674054},
 {'index': 6,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.005},
  'rmse': 0.29671325918853586},
 {'index': 7,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.01},
  'rmse': 0.26053927565601315},
 {'index': 8,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.02},
  'rmse': 0.28471073997471036},
 {'index': 9,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.05},
  'rmse': 0.34324741130191005},
 {'index': 10,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.1},
  'rmse': 0.3774793261411331},
 {'index': 11,
  'model_type': 'Lasso',
  'hyperparams': {'alpha': 0.2},
  'rmse': 0.5313726916801317},
 {'index': 12,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 1},
  'rmse': 0.274791406275937},
 {'index': 13,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 2},
  'rmse': 0.2667811078874242},
 {'index': 14,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 3},
  'rmse': 0.32722851294618766},
 {'index': 15,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 5},
  'rmse': 0.27431612464288047},
 {'index': 16,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 7},
  'rmse': 0.2583906647995346},
 {'index': 17,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 10},
  'rmse': 0.2653915182964347},
 {'index': 18,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 15},
  'rmse': 0.3008588245844687},
 {'index': 19,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 20},
  'rmse': 0.2622551851519705},
 {'index': 20,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 30},
  'rmse': 0.8964576365455814},
 {'index': 21,
  'model_type': 'Ridge',
  'hyperparams': {'alpha': 50},
  'rmse': 0.7918415432135305},
 {'index': 22,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 0.1, 'degree': 3, 'kernel': 'poly'},
  'rmse': 0.30413401701908416},
 {'index': 23,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 1, 'degree': 3, 'kernel': 'poly'},
  'rmse': 0.38796143986421605},
 {'index': 24,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 10, 'degree': 3, 'kernel': 'poly'},
  'rmse': 0.8359538667074695},
 {'index': 25,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 0.1, 'kernel': 'rbf'},
  'rmse': 0.35591709148388817},
 {'index': 26,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 1, 'kernel': 'rbf'},
  'rmse': 0.4369372938666854},
 {'index': 27,
  'model_type': 'KernelRidge',
  'hyperparams': {'alpha': 10, 'kernel': 'rbf'},
  'rmse': 0.6477949048304251},
 {'index': 28,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 3, 'n_estimators': 10},
  'rmse': 0.48316045829267057},
 {'index': 29,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 10},
  'rmse': 0.36481943858227034},
 {'index': 30,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 20},
  'rmse': 0.2897772097917187},
 {'index': 31,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 50},
  'rmse': 0.31424632353868553},
 {'index': 32,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 8, 'n_estimators': 50},
  'rmse': 0.26891537521403913},
 {'index': 33,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 8, 'n_estimators': 100},
  'rmse': 0.3050162246606871},
 {'index': 34,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 100},
  'rmse': 0.45434734706834556},
 {'index': 35,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 8, 'n_estimators': 100},
  'rmse': 0.2753702275867707},
 {'index': 36,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 16, 'n_estimators': 200},
  'rmse': 0.2782184113889237},
 {'index': 37,
  'model_type': 'RandomForestRegressor',
  'hyperparams': {'max_depth': 32, 'n_estimators': 1000},
  'rmse': 0.23253547298298005},
 {'index': 38,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 3, 'n_estimators': 100, 'learning_rate': 0.1},
  'rmse': 0.3173875292248438},
 {'index': 39,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 100, 'learning_rate': 0.1},
  'rmse': 0.232863508655864},
 {'index': 40,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 3, 'n_estimators': 200, 'learning_rate': 0.1},
  'rmse': 0.30695122712655953},
 {'index': 41,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 10, 'n_estimators': 200, 'learning_rate': 0.2},
  'rmse': 0.3395619987867347},
 {'index': 42,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 5, 'n_estimators': 500, 'learning_rate': 0.1},
  'rmse': 0.3636496691367162},
 {'index': 43,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 10, 'n_estimators': 500, 'learning_rate': 0.01},
  'rmse': 0.2826685522889321},
 {'index': 44,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 10, 'n_estimators': 1000, 'learning_rate': 0.1},
  'rmse': 0.4209767228512498},
 {'index': 45,
  'model_type': 'XGBRegressor',
  'hyperparams': {'max_depth': 32, 'n_estimators': 2000, 'learning_rate': 0.1},
  'rmse': 0.3450224401105828},
 {'index': 46,
  'model_type': 'GaussianProcessRegressor',
  'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)},
  'rmse': 0.20052852390943635},
 {'index': 47,
  'model_type': 'GaussianProcessRegressor',
  'hyperparams': {'kernel': Matern(length_scale=1, nu=1.5)},
  'rmse': 0.21974053165354152},
 {'index': 48,
  'model_type': 'GaussianProcessRegressor',
  'hyperparams': {'kernel': RBF(length_scale=1)},
  'rmse': 0.24904687682427573},
 {'index': 49,
  'model_type': 'GaussianProcessRegressor',
  'hyperparams': {'kernel': RBF(length_scale=1)},
  'rmse': 0.2371973841890745},
 {'index': 50,
  'model_type': 'MLP_PyTorch',
  'hyperparams': {'n_layers': 2,
   'layer_size': 5,
   'lr': 0.01,
   'l2_reg': 0.01,
   'input_dim': 516,
   'output_dim': 1},
  'rmse': 1.0029479265213013},
 {'index': 51,
  'model_type': 'MLP_PyTorch',
  'hyperparams': {'n_layers': 2,
   'layer_size': 10,
   'lr': 0.001,
   'l2_reg': 0.1,
   'input_dim': 516,
   'output_dim': 1},
  'rmse': 0.989759624004364},
 {'index': 52,
  'model_type': 'MLP_PyTorch',
  'hyperparams': {'n_layers': 3,
   'layer_size': 10,
   'lr': 0.001,
   'l2_reg': 0.1,
   'input_dim': 516,
   'output_dim': 1},
  'rmse': 1.0059338808059692},
 {'index': 53,
  'model_type': 'MLP_PyTorch',
  'hyperparams': {'n_layers': 3,
   'layer_size': 10,
   'lr': 0.0005,
   'l2_reg': 0.1,
   'input_dim': 516,
   'output_dim': 1},
  'rmse': 1.0044853687286377},
 {'index': 54,
  'model_type': 'ResNet',
  'hyperparams': None,
  'rmse': 0.9616740345954895},
 {'index': 55,
  'model_type': 'ResNet',
  'hyperparams': None,
  'rmse': 0.9884374737739563},
 {'index': 56,
  'model_type': 'ResNet',
  'hyperparams': None,
  'rmse': 0.9474957585334778},
 {'index': 57,
  'model_type': 'ResNet',
  'hyperparams': None,
  'rmse': 1.0045675039291382}]

In [22]:
models_df = pd.DataFrame(models_list)
models_df = models_df.sort_values('rmse', ascending=True).reset_index(drop=True)
final_models = models_df.head(10)
final_models

,index,model_type,hyperparams,rmse
0,46,GaussianProcessRegressor,"{'kernel': Matern(length_scale=1, nu=1.5)}",0.200529
1,47,GaussianProcessRegressor,"{'kernel': Matern(length_scale=1, nu=1.5)}",0.219741
2,37,RandomForestRegressor,"{'max_depth': 32, 'n_estimators': 1000}",0.232535
3,39,XGBRegressor,"{'max_depth': 5, 'n_estimators': 100, 'learnin...",0.232864
4,49,GaussianProcessRegressor,{'kernel': RBF(length_scale=1)},0.237197
5,48,GaussianProcessRegressor,{'kernel': RBF(length_scale=1)},0.249047
6,5,Lasso,{'alpha': 0.002},0.257297
7,16,Ridge,{'alpha': 7},0.258391
8,7,Lasso,{'alpha': 0.01},0.260539
9,19,Ridge,{'alpha': 20},0.262255

In [23]:
def softmax(series):
    exp_x = np.exp(series - series.max())
    return exp_x / exp_x.sum()

In [24]:
final_models['weights'] = softmax(-final_models['rmse'])
final_models

/tmp/ipykernel_387435/2114309755.py:1: SettingWithCopyWarning:
A value is trying to be set on a copy of a slice from a DataFrame.
Try using .loc[row_indexer,col_indexer] = value instead

See the caveats in the documentation: https://pandas.pydata.org/pandas-docs/stable/user_guide/indexing.html#returning-a-view-versus-a-copy
  final_models['weights'] = softmax(-final_models['rmse'])

,index,model_type,hyperparams,rmse,weights
0,46,GaussianProcessRegressor,"{'kernel': Matern(length_scale=1, nu=1.5)}",0.200529,0.104115
1,47,GaussianProcessRegressor,"{'kernel': Matern(length_scale=1, nu=1.5)}",0.219741,0.102134
2,37,RandomForestRegressor,"{'max_depth': 32, 'n_estimators': 1000}",0.232535,0.100835
3,39,XGBRegressor,"{'max_depth': 5, 'n_estimators': 100, 'learnin...",0.232864,0.100802
4,49,GaussianProcessRegressor,{'kernel': RBF(length_scale=1)},0.237197,0.100366
5,48,GaussianProcessRegressor,{'kernel': RBF(length_scale=1)},0.249047,0.099184
6,5,Lasso,{'alpha': 0.002},0.257297,0.098369
7,16,Ridge,{'alpha': 7},0.258391,0.098262
8,7,Lasso,{'alpha': 0.01},0.260539,0.098051
9,19,Ridge,{'alpha': 20},0.262255,0.097883

In [25]:
rmse = sum(final_models['rmse']*final_models['weights'])
rmse

0.2406661136800385